import fs from 'fs';

const newEntries = {
  "i'd": { "word": "I'd", "phonetic": "[aɪd]", "meanings": ["1. I would / I had의 축약형"] },
  "check": { "word": "check", "phonetic": "[tʃek]", "meanings": ["1. 확인하다", "2. (수하물을) 부치다"] },
  "e-ticket": { "word": "e-ticket", "phonetic": "[ˈiː tɪkɪt]", "meanings": ["1. 전자 항공권"] },
  "possible": { "word": "possible", "phonetic": "[ˈpɑːsəbl]", "meanings": ["1. 가능한"] },
  "window": { "word": "window", "phonetic": "[ˈwɪndoʊ]", "meanings": ["1. 창문", "2. 창가"] },
  "seat": { "word": "seat", "phonetic": "[siːt]", "meanings": ["1. 좌석, 자리"] },
  "prefer": { "word": "prefer", "phonetic": "[prɪˈfɜːr]", "meanings": ["1. 선호하다", "2. ~을 더 좋아하다"] },
  "aisle": { "word": "aisle", "phonetic": "[aɪl]", "meanings": ["1. 통로"] },
  "family": { "word": "family", "phonetic": "[ˈfæməli]", "meanings": ["1. 가족"] },
  "sit": { "word": "sit", "phonetic": "[sɪt]", "meanings": ["1. 앉다"] },
  "together": { "word": "together", "phonetic": "[təˈɡeðər]", "meanings": ["1. 함께, 같이"] },
  "bags": { "word": "bags", "phonetic": "[bæɡz]", "meanings": ["1. 가방들"] },
  "only": { "word": "only", "phonetic": "[ˈoʊnli]", "meanings": ["1. 오직, 단지"] },
  "carry-on": { "word": "carry-on", "phonetic": "[ˈkæri ɑːn]", "meanings": ["1. 기내 수하물", "2. 기내에 반입할 수 있는"] },
  "place": { "word": "place", "phonetic": "[pleɪs]", "meanings": ["1. 장소", "2. 놓다, 두다"] },
  "scale": { "word": "scale", "phonetic": "[skeɪl]", "meanings": ["1. 저울", "2. 규모"] },
  "overweight": { "word": "overweight", "phonetic": "[ˌoʊvərˈweɪt]", "meanings": ["1. 중량 초과의", "2. 과체중의"] },
  "excess": { "word": "excess", "phonetic": "[ɪkˈses]", "meanings": ["1. 초과, 과잉", "2. 초과한"] },
  "by": { "word": "by", "phonetic": "[baɪ]", "meanings": ["1. ~에 의하여", "2. ~옆에"] },
  "mark": { "word": "mark", "phonetic": "[mɑːrk]", "meanings": ["1. 표시하다", "2. 자국"] },
  "as": { "word": "as", "phonetic": "[æz]", "meanings": ["1. ~로서", "2. ~만큼"] },
  "fragile": { "word": "fragile", "phonetic": "[ˈfrædʒl]", "meanings": ["1. 부서지기 쉬운", "2. 취약한"] },
  "pick": { "word": "pick", "phonetic": "[pɪk]", "meanings": ["1. 고르다", "2. 줍다 (pick up)"] },
  "layover": { "word": "layover", "phonetic": "[ˈleɪoʊvər]", "meanings": ["1. 도중하차, 경유"] },
  "final": { "word": "final", "phonetic": "[ˈfaɪnl]", "meanings": ["1. 마지막의", "2. 최종적인"] },
  "destination": { "word": "destination", "phonetic": "[ˌdestɪˈneɪʃn]", "meanings": ["1. 목적지, 도착지"] },
  "self": { "word": "self", "phonetic": "[self]", "meanings": ["1. 자신", "2. 자기"] },
  "kiosk": { "word": "kiosk", "phonetic": "[ˈkiːɑːsk]", "meanings": ["1. 무인 단말기, 키오스크"] },
  "print": { "word": "print", "phonetic": "[prɪnt]", "meanings": ["1. 인쇄하다", "2. 출력하다"] },
  "boarding": { "word": "boarding", "phonetic": "[ˈbɔːrdɪŋ]", "meanings": ["1. 탑승"] },
  "pass": { "word": "pass", "phonetic": "[pæs]", "meanings": ["1. 지나가다", "2. 통과하다", "3. 탑승권 (boarding pass)"] },
  "has": { "word": "has", "phonetic": "[hæz]", "meanings": ["1. have의 3인칭 단수형"] },
  "changed": { "word": "changed", "phonetic": "[tʃeɪndʒd]", "meanings": ["1. 변경된"] },
  "when": { "word": "when", "phonetic": "[wen]", "meanings": ["1. 언제", "2. ~할 때"] },
  "standby": { "word": "standby", "phonetic": "[ˈstændbaɪ]", "meanings": ["1. 대기", "2. 예비품"] },
  "list": { "word": "list", "phonetic": "[lɪst]", "meanings": ["1. 목록, 명단"] },
  "security": { "word": "security", "phonetic": "[səˈkjʊrəti]", "meanings": ["1. 보안, 경비", "2. 안전"] },
  "shoes": { "word": "shoes", "phonetic": "[ʃuːz]", "meanings": ["1. 신발"] },
  "empty": { "word": "empty", "phonetic": "[ˈempti]", "meanings": ["1. 비어 있는", "2. 비우다"] },
  "pockets": { "word": "pockets", "phonetic": "[ˈpɑːkɪts]", "meanings": ["1. 주머니들"] },
  "laptop": { "word": "laptop", "phonetic": "[ˈlæptɑːp]", "meanings": ["1. 노트북 컴퓨터"] },
  "out": { "word": "out", "phonetic": "[aʊt]", "meanings": ["1. 밖으로", "2. 밖에"] },
  "of": { "word": "of", "phonetic": "[əv]", "meanings": ["1. ~의", "2. ~에 대한"] },
  "bottle": { "word": "bottle", "phonetic": "[ˈbɑːtl]", "meanings": ["1. 병"] },
  "throw": { "word": "throw", "phonetic": "[θroʊ]", "meanings": ["1. 던지다", "2. 버리다 (throw away)"] },
  "away": { "word": "away", "phonetic": "[əˈweɪ]", "meanings": ["1. 떨어져", "2. 다른 데로"] },
  "metal": { "word": "metal", "phonetic": "[ˈmetl]", "meanings": ["1. 금속"] },
  "implant": { "word": "implant", "phonetic": "[ɪmˈplænt]", "meanings": ["1. 이식하다", "2. 이식물"] },
  "plastic": { "word": "plastic", "phonetic": "[ˈplæstɪk]", "meanings": ["1. 플라스틱", "2. 비닐"] },
  "liquids": { "word": "liquids", "phonetic": "[ˈlɪkwɪdz]", "meanings": ["1. 액체류"] },
  "remove": { "word": "remove", "phonetic": "[rɪˈmuːv]", "meanings": ["1. 제거하다", "2. 벗다"] },
  "belt": { "word": "belt", "phonetic": "[belt]", "meanings": ["1. 벨트, 허리띠"] },
  "step": { "word": "step", "phonetic": "[step]", "meanings": ["1. 걸음", "2. 걷다"] },
  "through": { "word": "through", "phonetic": "[θruː]", "meanings": ["1. ~을 통과하여", "2. ~을 통하여"] },
  "scanner": { "word": "scanner", "phonetic": "[ˈskænər]", "meanings": ["1. 스캐너, 검색기"] },
  "purpose": { "word": "purpose", "phonetic": "[ˈpɜːrpəs]", "meanings": ["1. 목적, 의도"] },
  "visit": { "word": "visit", "phonetic": "[ˈvɪzɪt]", "meanings": ["1. 방문하다", "2. 방문"] },
  "sightseeing": { "word": "sightseeing", "phonetic": "[ˈsaɪtsiːɪŋ]", "meanings": ["1. 관광, 구경"] },
  "business": { "word": "business", "phonetic": "[ˈbɪznəs]", "meanings": ["1. 사업", "2. 업무"] },
  "visiting": { "word": "visiting", "phonetic": "[ˈvɪzɪtɪŋ]", "meanings": ["1. 방문하는"] },
  "friends": { "word": "friends", "phonetic": "[frendz]", "meanings": ["1. 친구들"] },
  "stay": { "word": "stay", "phonetic": "[steɪ]", "meanings": ["1. 머무르다", "2. 체류"] },
  "week": { "word": "week", "phonetic": "[wiːk]", "meanings": ["1. 주, 일주일"] },
  "be": { "word": "be", "phonetic": "[bi]", "meanings": ["1. ~이다", "2. 있다"] },
  "staying": { "word": "staying", "phonetic": "[ˈsteɪɪŋ]", "meanings": ["1. 머무르는 중인"] },
  "hilton": { "word": "hilton", "phonetic": "[ˈhɪltən]", "meanings": ["1. 힐튼 (호텔 이름)"] },
  "hotel": { "word": "hotel", "phonetic": "[hoʊˈtel]", "meanings": ["1. 호텔"] },
  "traveling": { "word": "traveling", "phonetic": "[ˈtrævəlɪŋ]", "meanings": ["1. 여행하는"] },
  "alone": { "word": "alone", "phonetic": "[əˈloʊn]", "meanings": ["1. 혼자", "2. 홀로"] },
  "first": { "word": "first", "phonetic": "[fɜːrst]", "meanings": ["1. 첫 번째의", "2. 처음으로"] },
  "anything": { "word": "anything", "phonetic": "[ˈeniθɪŋ]", "meanings": ["1. 무엇이든", "2. 아무것도"] },
  "start": { "word": "start", "phonetic": "[stɑːrt]", "meanings": ["1. 시작하다", "2. 출발하다"] },
  "started": { "word": "started", "phonetic": "[ˈstɑːrtɪd]", "meanings": ["1. 시작된"] },
  "yet": { "word": "yet", "phonetic": "[jet]", "meanings": ["1. 아직", "2. 벌써"] },
  "wrong": { "word": "wrong", "phonetic": "[rɔːŋ]", "meanings": ["1. 틀린", "2. 잘못된"] },
  "board": { "word": "board", "phonetic": "[bɔːrd]", "meanings": ["1. 탑승하다", "2. 판"] },
  "now": { "word": "now", "phonetic": "[naʊ]", "meanings": ["1. 지금", "2. 이제"] },
  "priority": { "word": "priority", "phonetic": "[praɪˈɔːrəti]", "meanings": ["1. 우선순위", "2. 우선권"] },
  "line": { "word": "line", "phonetic": "[laɪn]", "meanings": ["1. 선", "2. 줄"] },
  "someone": { "word": "someone", "phonetic": "[ˈsʌmwʌn]", "meanings": ["1. 누군가"] },
  "sitting": { "word": "sitting", "phonetic": "[ˈsɪtɪŋ]", "meanings": ["1. 앉아 있는"] },
  "blanket": { "word": "blanket", "phonetic": "[ˈblæŋkɪt]", "meanings": ["1. 담요"] },
  "kind": { "word": "kind", "phonetic": "[kaɪnd]", "meanings": ["1. 종류", "2. 친절한"] },
  "drinks": { "word": "drinks", "phonetic": "[drɪŋks]", "meanings": ["1. 음료들"] },
  "beef": { "word": "beef", "phonetic": "[biːf]", "meanings": ["1. 소고기"] },
  "chicken": { "word": "chicken", "phonetic": "[ˈtʃɪkɪn]", "meanings": ["1. 닭고기"] },
  "snack": { "word": "snack", "phonetic": "[snæk]", "meanings": ["1. 간식", "2. 스낵"] },
  "little": { "word": "little", "phonetic": "[ˈlɪtl]", "meanings": ["1. 작은", "2. 약간의"] },
  "air": { "word": "air", "phonetic": "[er]", "meanings": ["1. 공기", "2. 항공의"] },
  "sick": { "word": "sick", "phonetic": "[sɪk]", "meanings": ["1. 아픈", "2. 멀미가 나는"] },
  "lavatory": { "word": "lavatory", "phonetic": "[ˈlævətɔːri]", "meanings": ["1. 화장실 (기내 등)"] },
  "occupied": { "word": "occupied", "phonetic": "[ˈɑːkjupaɪd]", "meanings": ["1. 사용 중인", "2. 바쁜"] },
  "fasten": { "word": "fasten", "phonetic": "[ˈfæsn]", "meanings": ["1. 매다", "2. 고정하다"] },
  "seatbelt": { "word": "seatbelt", "phonetic": "[ˈsiːtbelt]", "meanings": ["1. 안전벨트"] },
  "until": { "word": "until", "phonetic": "[ənˈtɪl]", "meanings": ["1. ~할 때까지"] },
  "land": { "word": "land", "phonetic": "[lænd]", "meanings": ["1. 착륙하다", "2. 땅"] },
  "customs": { "word": "customs", "phonetic": "[ˈkʌstəmz]", "meanings": ["1. 세관"] },
  "declaration": { "word": "declaration", "phonetic": "[ˌdekləˈreɪʃn]", "meanings": ["1. 선언", "2. 신고서"] },
  "form": { "word": "form", "phonetic": "[fɔːrm]", "meanings": ["1. 형태", "2. 서식, 양식"] },
  "pen": { "word": "pen", "phonetic": "[pen]", "meanings": ["1. 펜"] },
  "down": { "word": "down", "phonetic": "[daʊn]", "meanings": ["1. 아래로"] },
  "conditioning": { "word": "conditioning", "phonetic": "[kənˈdɪʃənɪŋ]", "meanings": ["1. 조절 (air conditioning: 에어컨)"] },
  "recline": { "word": "recline", "phonetic": "[rɪˈklaɪn]", "meanings": ["1. 비스듬히 기대다", "2. (의자를) 뒤로 젖히다"] },
  "put": { "word": "put", "phonetic": "[pʊt]", "meanings": ["1. 놓다", "2. 두다"] },
  "upright": { "word": "upright", "phonetic": "[ˈʌpraɪt]", "meanings": ["1. 똑바른", "2. 꼿꼿한"] },
  "carousel": { "word": "carousel", "phonetic": "[ˌkærəˈsel]", "meanings": ["1. 회전목마", "2. (공항의) 수하물 컨베이어 벨트"] },
  "hasn't": { "word": "hasn't", "phonetic": "[ˈhæznt]", "meanings": ["1. has not의 축약형"] },
  "arrived": { "word": "arrived", "phonetic": "[əˈraɪvd]", "meanings": ["1. 도착했다"] },
  "damaged": { "word": "damaged", "phonetic": "[ˈdæmɪdʒd]", "meanings": ["1. 손상된", "2. 파손된"] },
  "transfer": { "word": "transfer", "phonetic": "[trænsˈfɜːr]", "meanings": ["1. 이동하다", "2. 환승하다"] },
  "desk": { "word": "desk", "phonetic": "[desk]", "meanings": ["1. 책상", "2. 안내 데스크"] },
  "again": { "word": "again", "phonetic": "[əˈɡen]", "meanings": ["1. 다시", "2. 또"] },
  "terminal": { "word": "terminal", "phonetic": "[ˈtɜːrmɪnl]", "meanings": ["1. 터미널", "2. 종착역"] },
  "shuttle": { "word": "shuttle", "phonetic": "[ˈʃʌtl]", "meanings": ["1. 셔틀", "2. 왕복 운행하는"] },
  "city": { "word": "city", "phonetic": "[ˈsɪti]", "meanings": ["1. 도시", "2. 시내"] },
  "currency": { "word": "currency", "phonetic": "[ˈkɜːrənsi]", "meanings": ["1. 통화", "2. 화폐"] },
  "tourist": { "word": "tourist", "phonetic": "[ˈtʊrɪst]", "meanings": ["1. 관광객"] },
  "center": { "word": "center", "phonetic": "[ˈsentər]", "meanings": ["1. 중심", "2. 센터"] }
};

const dictionaryData = JSON.parse(fs.readFileSync('./src/dictionary.json', 'utf8'));
Object.assign(dictionaryData, newEntries);
fs.writeFileSync('./src/dictionary.json', JSON.stringify(dictionaryData, null, 2));
console.log('Dictionary updated with missing words.');
