const fs = require('fs');

const newSentences = [
  { en: "I want to report a stolen bag.", ko: "가방 도난 신고를 하고 싶습니다.", tip: "가방을 도난당했을 때 경찰서에서 처음 하는 말입니다." },
  { en: "Where can I file a police report?", ko: "경찰 조서는 어디서 작성할 수 있나요?", tip: "조서 작성이 필요한 부서를 찾을 때 씁니다." },
  { en: "My wallet was pickpocketed on the subway.", ko: "지하철에서 소매치기를 당해 지갑을 잃어버렸어요.", tip: "소매치기 피해 사실과 장소를 함께 알릴 때 사용합니다." },
  { en: "I left my phone in a taxi.", ko: "택시에 휴대폰을 두고 내렸어요.", tip: "택시 분실물을 신고할 때 씁니다." },
  { en: "Someone broke into my rental car.", ko: "누군가 제 렌터카에 침입했어요.", tip: "차량 털이 피해를 신고할 때 사용합니다." },
  { en: "My passport is missing from my hotel room.", ko: "호텔 방에서 여권이 없어졌어요.", tip: "숙소 내 도난이 의심될 때 알립니다." },
  { en: "I need a police report for my insurance company.", ko: "보험사에 제출할 경찰 조서(폴리스 리포트)가 필요해요.", tip: "조서 발급 목적을 설명할 때 씁니다." },
  { en: "Can you give me a copy of the report?", ko: "조서 사본을 주실 수 있나요?", tip: "작성된 조서의 복사본을 요청할 때 사용합니다." },
  { en: "When did you realize it was missing?", ko: "언제 없어졌다는 것을 깨달았나요?", tip: "경찰이 분실 인지 시점을 물어볼 때 하는 말입니다." },
  { en: "I noticed it was gone about an hour ago.", ko: "약 한 시간 전에 없어진 걸 알았어요.", tip: "분실 인지 시점을 대답할 때 씁니다." },
  { en: "What was in your bag?", ko: "가방 안에 무엇이 들어 있었나요?", tip: "경찰이 분실물의 내용물을 확인할 때 묻습니다." },
  { en: "There was some cash, my credit cards, and my ID.", ko: "현금 약간과 신용카드, 신분증이 들어 있었어요.", tip: "잃어버린 물건들을 나열할 때 사용합니다." },
  { en: "How much cash was in the wallet?", ko: "지갑에 현금이 얼마나 있었나요?", tip: "정확한 피해 금액을 확인할 때 듣는 말입니다." },
  { en: "About two hundred dollars.", ko: "약 200달러 정도요.", tip: "대략적인 금액을 대답할 때 씁니다." },
  { en: "What color is your suitcase?", ko: "여행 가방은 무슨 색인가요?", tip: "분실물의 외형을 물어볼 때 씁니다." },
  { en: "It's a large black Samsonite suitcase.", ko: "크고 검은색인 샘소나이트 여행 가방입니다.", tip: "브랜드와 색상, 크기를 구체적으로 설명합니다." },
  { en: "Are there any distinguishing marks on it?", ko: "눈에 띄는 특징이 있나요?", tip: "분실물을 식별할 수 있는 특징을 물어볼 때 듣습니다." },
  { en: "It has a red ribbon tied to the handle.", ko: "손잡이에 빨간 리본이 묶여 있어요.", tip: "본인 물건만의 특징을 설명할 때 씁니다." },
  { en: "Can you describe the person who took it?", ko: "가져간 사람의 인상착의를 설명해 주실 수 있나요?", tip: "용의자 묘사를 요청받을 때 듣는 말입니다." },
  { en: "He was tall and wearing a black hoodie.", ko: "그는 키가 컸고 검은색 후드티를 입고 있었어요.", tip: "용의자의 키와 옷차림을 설명할 때 사용합니다." },
  { en: "I didn't get a good look at his face.", ko: "얼굴은 제대로 보지 못했어요.", tip: "용의자의 얼굴을 기억하지 못할 때 솔직하게 말합니다." },
  { en: "He ran away towards the station.", ko: "그가 역 쪽으로 도망갔어요.", tip: "도주 방향을 알려줄 때 씁니다." },
  { en: "Did anyone else see what happened?", ko: "무슨 일이 있었는지 본 다른 사람이 있나요?", tip: "경찰이 목격자 유무를 확인할 때 묻습니다." },
  { en: "I think the shop owner might have seen it.", ko: "가게 주인이 봤을지도 몰라요.", tip: "잠재적인 목격자를 지목할 때 사용합니다." },
  { en: "Are there any security cameras around there?", ko: "그 주변에 보안 카메라(CCTV)가 있나요?", tip: "CCTV 확인을 요청하거나 물어볼 때 씁니다." },
  { en: "Please fill out this lost property form.", ko: "이 분실물 신고서를 작성해 주세요.", tip: "경찰이 서류 작성을 안내할 때 하는 말입니다." },
  { en: "Do you have any identification with you?", ko: "신분증을 가지고 계신가요?", tip: "신원 확인을 위해 신분증을 요구할 때 듣습니다." },
  { en: "I only have a copy of my passport.", ko: "여권 사본만 가지고 있어요.", tip: "원본 신분증이 없을 때 대답합니다." },
  { en: "What is your contact number here?", ko: "이곳에서의 연락처가 어떻게 되나요?", tip: "현지 연락처를 물어볼 때 듣는 말입니다." },
  { en: "You can reach me at my hotel.", ko: "제 호텔로 연락 주시면 됩니다.", tip: "현지 번호가 없을 때 숙소 연락처를 안내합니다." },
  { en: "My hotel is the Grand Plaza in downtown.", ko: "제 호텔은 시내에 있는 그랜드 플라자입니다.", tip: "숙소 이름과 위치를 정확히 알려줄 때 씁니다." },
  { en: "How long will the investigation take?", ko: "조사는 얼마나 걸릴까요?", tip: "수사 소요 시간을 물어볼 때 사용합니다." },
  { en: "We will contact you if we find anything.", ko: "단서가 발견되면 연락드리겠습니다.", tip: "경찰이 수사 진행 상황 통보를 약속할 때 하는 말입니다." },
  { en: "Is there any chance of getting it back?", ko: "되찾을 가능성이 있을까요?", tip: "물건을 찾을 수 있을지 물어볼 때 씁니다." },
  { en: "I've already canceled my credit cards.", ko: "신용카드는 이미 정지시켰어요.", tip: "2차 피해 방지 조치를 완료했음을 알릴 때 사용합니다." },
  { en: "I need to contact my embassy immediately.", ko: "즉시 대사관에 연락해야 해요.", tip: "대사관의 도움이 시급할 때 경찰에 알립니다." },
  { en: "Can you provide a translator?", ko: "통역사를 제공해 주실 수 있나요?", tip: "의사소통이 어려워 통역 지원을 요청할 때 씁니다." },
  { en: "I don't speak English very well.", ko: "저는 영어를 잘하지 못합니다.", tip: "언어 장벽을 솔직하게 알릴 때 사용합니다." },
  { en: "Could you speak a little slower, please?", ko: "조금만 천천히 말씀해 주시겠어요?", tip: "경찰의 말이 너무 빠를 때 정중히 요청합니다." },
  { en: "I was walking down the street when it happened.", ko: "사건이 발생했을 때 저는 길을 걷고 있었어요.", tip: "사건 당시의 상황을 묘사하기 시작할 때 씁니다." },
  { en: "Two men approached me from behind.", ko: "두 남자가 뒤에서 저에게 다가왔어요.", tip: "용의자의 접근 방식을 설명할 때 사용합니다." },
  { en: "One of them bumped into me intentionally.", ko: "그들 중 한 명이 고의로 저와 부딪혔어요.", tip: "소매치기 수법(고의 충돌)을 설명할 때 씁니다." },
  { en: "I felt someone's hand in my pocket.", ko: "누군가의 손이 제 주머니에 들어오는 것을 느꼈어요.", tip: "소매치기 순간의 느낌을 진술할 때 사용합니다." },
  { en: "I shouted for help, but no one came.", ko: "도와달라고 소리쳤지만 아무도 오지 않았어요.", tip: "당시의 대처와 주변 상황을 설명할 때 씁니다." },
  { en: "My laptop was in the backpack.", ko: "제 노트북이 배낭 안에 있었어요.", tip: "도난당한 주요 물품을 구체적으로 언급할 때 사용합니다." },
  { en: "It's a silver MacBook Pro.", ko: "은색 맥북 프로입니다.", tip: "전자기기의 모델과 색상을 정확히 설명합니다." },
  { en: "The serial number is written on this paper.", ko: "일련번호가 이 종이에 적혀 있어요.", tip: "기기 추적을 위해 일련번호를 제공할 때 씁니다." },
  { en: "I have the receipt for the stolen camera.", ko: "도난당한 카메라의 영수증을 가지고 있어요.", tip: "소유권 및 가치 증명을 위해 영수증을 제시할 때 사용합니다." },
  { en: "The camera lens was also attached.", ko: "카메라 렌즈도 장착되어 있었어요.", tip: "추가적인 도난 물품을 설명할 때 씁니다." },
  { en: "My designer sunglasses were in the case.", ko: "명품 선글라스가 케이스 안에 있었어요.", tip: "고가의 분실물을 신고할 때 사용합니다." },
  { en: "I left my purse on the chair at the cafe.", ko: "카페 의자에 지갑을 두고 왔어요.", tip: "분실 장소와 상황을 설명할 때 씁니다." },
  { en: "When I came back, it was gone.", ko: "돌아와 보니 없어져 있었어요.", tip: "분실 사실을 인지한 순간을 진술할 때 사용합니다." },
  { en: "I asked the staff, but they didn't see anything.", ko: "직원에게 물어봤지만 아무것도 보지 못했다고 했어요.", tip: "자체적으로 확인한 내용을 경찰에 알릴 때 씁니다." },
  { en: "I tracked my phone using GPS.", ko: "GPS를 이용해 제 휴대폰을 추적했어요.", tip: "위치 추적 결과를 경찰에 알릴 때 사용합니다." },
  { en: "The location shows it's in this neighborhood.", ko: "위치가 이 동네로 나와요.", tip: "추적된 대략적인 위치를 알려줄 때 씁니다." },
  { en: "Can you send an officer to that location?", ko: "그 위치로 경찰관을 보내주실 수 있나요?", tip: "추적된 위치로 출동을 요청할 때 사용합니다." },
  { en: "I am leaving the country tomorrow.", ko: "저는 내일 출국합니다.", tip: "시간이 촉박함을 경찰에 알릴 때 씁니다." },
  { en: "Can you email me the report number?", ko: "조서 번호를 이메일로 보내주실 수 있나요?", tip: "출국 후 조서 번호를 받기 위해 요청할 때 사용합니다." },
  { en: "What should I do next?", ko: "다음에는 어떻게 해야 하나요?", tip: "신고 후 향후 절차를 물어볼 때 씁니다." },
  { en: "Do I need to come back to the station?", ko: "경찰서에 다시 와야 하나요?", tip: "재방문 필요 여부를 확인할 때 사용합니다." },
  { en: "Is this the lost and found department?", ko: "여기가 분실물 센터인가요?", tip: "경찰서 내 분실물 담당 부서를 찾을 때 묻습니다." },
  { en: "I'm looking for a lost umbrella.", ko: "잃어버린 우산을 찾고 있어요.", tip: "특정 분실물을 찾으러 왔음을 알릴 때 씁니다." },
  { en: "Has anyone turned in a brown leather jacket?", ko: "갈색 가죽 재킷 들어온 것 있나요?", tip: "누군가 습득하여 제출했는지 물어볼 때 사용합니다." },
  { en: "I lost my wedding ring at the beach.", ko: "해변에서 결혼반지를 잃어버렸어요.", tip: "귀중품 분실 장소를 설명할 때 씁니다." },
  { en: "It has my initials engraved inside.", ko: "안쪽에 제 이니셜이 새겨져 있어요.", tip: "반지 등 귀금속의 고유한 특징을 설명할 때 사용합니다." },
  { en: "I dropped my keys somewhere in the park.", ko: "공원 어딘가에 열쇠를 떨어뜨렸어요.", tip: "정확한 분실 위치를 모를 때 씁니다." },
  { en: "They are on a blue keychain.", ko: "파란색 열쇠고리에 끼워져 있어요.", tip: "열쇠의 특징을 설명할 때 사용합니다." },
  { en: "I want to report a scam.", ko: "사기를 당해서 신고하고 싶습니다.", tip: "사기 피해를 신고할 때 씁니다." },
  { en: "I bought fake tickets from a street vendor.", ko: "노점상에게서 가짜 티켓을 샀어요.", tip: "사기 수법을 구체적으로 설명할 때 사용합니다." },
  { en: "I paid him in cash.", ko: "그에게 현금으로 지불했어요.", tip: "결제 수단을 진술할 때 씁니다." },
  { en: "He told me to wait, but he never returned.", ko: "기다리라고 하더니 돌아오지 않았어요.", tip: "사기꾼의 행동을 묘사할 때 사용합니다." },
  { en: "I was overcharged by a taxi driver.", ko: "택시 기사에게 바가지를 썼어요.", tip: "부당한 요금 청구 피해를 신고할 때 씁니다." },
  { en: "The driver refused to use the meter.", ko: "기사가 미터기 사용을 거부했어요.", tip: "택시 기사의 불법 행위를 진술할 때 사용합니다." },
  { en: "I took a picture of the license plate.", ko: "번호판 사진을 찍어두었어요.", tip: "증거 자료가 있음을 경찰에 알릴 때 씁니다." },
  { en: "Here is the photo on my phone.", ko: "제 휴대폰에 있는 사진이 여기 있습니다.", tip: "경찰에게 증거 사진을 보여줄 때 사용합니다." },
  { en: "I want to press charges.", ko: "고소(처벌)를 원합니다.", tip: "가해자에 대한 법적 처벌 의사를 밝힐 때 씁니다." },
  { en: "I don't want to press charges, I just want my things back.", ko: "처벌은 원하지 않고, 제 물건만 되찾고 싶어요.", tip: "처벌보다는 피해 복구에 목적이 있음을 알릴 때 사용합니다." },
  { en: "I feel very unsafe right now.", ko: "지금 너무 불안해요.", tip: "신변의 위협이나 불안감을 느낄 때 경찰에 호소합니다." },
  { en: "Can someone escort me to my hotel?", ko: "누군가 저를 호텔까지 에스코트해 주실 수 있나요?", tip: "안전을 위해 동행을 요청할 때 씁니다." },
  { en: "I am traveling alone.", ko: "저는 혼자 여행 중입니다.", tip: "동행자가 없음을 알려 추가적인 보호를 요청할 때 사용합니다." },
  { en: "My travel companion is at the hospital.", ko: "제 일행은 병원에 있어요.", tip: "일행의 위치와 상황을 설명할 때 씁니다." },
  { en: "We were attacked by a group of teenagers.", ko: "10대 무리에게 공격을 받았어요.", tip: "폭행 피해 사실과 가해자를 진술할 때 사용합니다." },
  { en: "They threatened us with a knife.", ko: "그들이 칼로 우리를 위협했어요.", tip: "무기를 사용한 위협 사실을 알릴 때 씁니다." },
  { en: "They demanded our money and phones.", ko: "그들이 돈과 휴대폰을 요구했어요.", tip: "강도의 요구 사항을 진술할 때 사용합니다." },
  { en: "I handed over everything I had.", ko: "가진 것을 모두 넘겨주었어요.", tip: "피해 상황을 설명할 때 씁니다." },
  { en: "I am physically unharmed, but very shocked.", ko: "신체적으로 다치진 않았지만, 너무 큰 충격을 받았어요.", tip: "현재의 신체적, 심리적 상태를 알릴 때 사용합니다." },
  { en: "Do you need medical attention?", ko: "의학적 치료가 필요하신가요?", tip: "경찰이 부상 여부를 확인할 때 묻는 말입니다." },
  { en: "No, I don't need an ambulance.", ko: "아니요, 구급차는 필요 없습니다.", tip: "병원 치료가 필요 없음을 대답할 때 씁니다." },
  { en: "Please sign at the bottom of the page.", ko: "페이지 하단에 서명해 주세요.", tip: "조서 작성을 마치고 서명을 요구받을 때 듣습니다." },
  { en: "Read the statement carefully before signing.", ko: "서명하기 전에 진술서를 주의 깊게 읽어보세요.", tip: "서명 전 내용 확인을 당부받을 때 듣는 말입니다." },
  { en: "Is everything written here correct?", ko: "여기에 적힌 내용이 모두 맞습니까?", tip: "진술 내용의 정확성을 최종 확인할 때 경찰이 묻습니다." },
  { en: "Yes, that is exactly what happened.", ko: "네, 정확히 그렇게 일어난 일입니다.", tip: "진술 내용이 사실과 일치함을 확인해 줄 때 씁니다." },
  { en: "I want to add one more detail.", ko: "한 가지 세부 사항을 더 추가하고 싶어요.", tip: "조서에 누락된 내용을 덧붙일 때 사용합니다." },
  { en: "He had a scar on his left cheek.", ko: "그는 왼쪽 뺨에 흉터가 있었어요.", tip: "용의자의 결정적인 신체적 특징을 묘사할 때 씁니다." },
  { en: "He was wearing a baseball cap.", ko: "그는 야구 모자를 쓰고 있었어요.", tip: "용의자의 착장을 추가로 설명할 때 사용합니다." },
  { en: "The car was a dark blue sedan.", ko: "그 차는 짙은 파란색 세단이었어요.", tip: "도주 차량의 색상과 차종을 설명할 때 씁니다." },
  { en: "I couldn't catch the license plate number.", ko: "번호판 번호는 보지 못했어요.", tip: "차량 번호를 기억하지 못할 때 솔직하게 말합니다." },
  { en: "Thank you for your assistance, officer.", ko: "도와주셔서 감사합니다, 경찰관님.", tip: "조사를 마치고 경찰에게 감사 인사를 할 때 씁니다." },
  { en: "I appreciate your quick response.", ko: "빠른 대처에 감사드립니다.", tip: "경찰의 신속한 도움에 고마움을 표할 때 사용합니다." },
  { en: "I hope you can catch the culprit.", ko: "범인을 꼭 잡을 수 있기를 바랍니다.", tip: "수사 성공을 기원하며 마무리 인사를 할 때 씁니다." }
];

const newWords = {
  "stolen": { en: "stolen", ko: "도난당한", type: "adjective" },
  "file": { en: "file", ko: "제출하다, (조서를) 작성하다", type: "verb" },
  "pickpocketed": { en: "pickpocketed", ko: "소매치기 당한", type: "adjective" },
  "subway": { en: "subway", ko: "지하철", type: "noun" },
  "rental": { en: "rental", ko: "임대의, 렌털", type: "adjective" },
  "company": { en: "company", ko: "회사", type: "noun" },
  "copy": { en: "copy", ko: "사본, 복사본", type: "noun" },
  "realize": { en: "realize", ko: "깨닫다, 알아차리다", type: "verb" },
  "noticed": { en: "noticed", ko: "알아차렸다 (notice의 과거형)", type: "verb" },
  "cash": { en: "cash", ko: "현금", type: "noun" },
  "suitcase": { en: "suitcase", ko: "여행 가방", type: "noun" },
  "distinguishing": { en: "distinguishing", ko: "특징적인, 구별되는", type: "adjective" },
  "marks": { en: "marks", ko: "표시, 자국", type: "noun" },
  "ribbon": { en: "ribbon", ko: "리본", type: "noun" },
  "tied": { en: "tied", ko: "묶인", type: "adjective" },
  "handle": { en: "handle", ko: "손잡이", type: "noun" },
  "hoodie": { en: "hoodie", ko: "후드티", type: "noun" },
  "face": { en: "face", ko: "얼굴", type: "noun" },
  "owner": { en: "owner", ko: "주인, 소유자", type: "noun" },
  "security": { en: "security", ko: "보안", type: "noun" },
  "cameras": { en: "cameras", ko: "카메라들", type: "noun" },
  "property": { en: "property", ko: "재산, 소유물", type: "noun" },
  "identification": { en: "identification", ko: "신분증", type: "noun" },
  "downtown": { en: "downtown", ko: "시내, 도심", type: "noun" },
  "investigation": { en: "investigation", ko: "조사, 수사", type: "noun" },
  "chance": { en: "chance", ko: "가능성, 기회", type: "noun" },
  "translator": { en: "translator", ko: "통역사", type: "noun" },
  "slower": { en: "slower", ko: "더 느리게", type: "adverb" },
  "approached": { en: "approached", ko: "접근했다 (approach의 과거형)", type: "verb" },
  "behind": { en: "behind", ko: "뒤에서", type: "adverb" },
  "bumped": { en: "bumped", ko: "부딪혔다 (bump의 과거형)", type: "verb" },
  "intentionally": { en: "intentionally", ko: "고의로, 의도적으로", type: "adverb" },
  "pocket": { en: "pocket", ko: "주머니", type: "noun" },
  "shouted": { en: "shouted", ko: "소리쳤다 (shout의 과거형)", type: "verb" },
  "laptop": { en: "laptop", ko: "노트북", type: "noun" },
  "backpack": { en: "backpack", ko: "배낭", type: "noun" },
  "silver": { en: "silver", ko: "은색의", type: "adjective" },
  "serial": { en: "serial", ko: "일련의", type: "adjective" },
  "written": { en: "written", ko: "적힌, 쓰인", type: "adjective" },
  "lens": { en: "lens", ko: "렌즈", type: "noun" },
  "attached": { en: "attached", ko: "부착된", type: "adjective" },
  "designer": { en: "designer", ko: "명품의, 디자이너의", type: "adjective" },
  "sunglasses": { en: "sunglasses", ko: "선글라스", type: "noun" },
  "case": { en: "case", ko: "케이스, 상자", type: "noun" },
  "purse": { en: "purse", ko: "지갑, 핸드백", type: "noun" },
  "chair": { en: "chair", ko: "의자", type: "noun" },
  "staff": { en: "staff", ko: "직원", type: "noun" },
  "tracked": { en: "tracked", ko: "추적했다 (track의 과거형)", type: "verb" },
  "location": { en: "location", ko: "위치", type: "noun" },
  "neighborhood": { en: "neighborhood", ko: "동네, 이웃", type: "noun" },
  "officer": { en: "officer", ko: "경찰관, 장교", type: "noun" },
  "leaving": { en: "leaving", ko: "떠나는", type: "adjective" },
  "country": { en: "country", ko: "나라, 국가", type: "noun" },
  "email": { en: "email", ko: "이메일을 보내다", type: "verb" },
  "next": { en: "next", ko: "다음에", type: "adverb" },
  "department": { en: "department", ko: "부서", type: "noun" },
  "umbrella": { en: "umbrella", ko: "우산", type: "noun" },
  "turned": { en: "turned", ko: "제출했다, 돌렸다 (turn의 과거형)", type: "verb" },
  "leather": { en: "leather", ko: "가죽", type: "noun" },
  "jacket": { en: "jacket", ko: "재킷", type: "noun" },
  "wedding": { en: "wedding", ko: "결혼", type: "noun" },
  "ring": { en: "ring", ko: "반지", type: "noun" },
  "beach": { en: "beach", ko: "해변", type: "noun" },
  "initials": { en: "initials", ko: "이니셜, 머리글자", type: "noun" },
  "engraved": { en: "engraved", ko: "새겨진", type: "adjective" },
  "inside": { en: "inside", ko: "안쪽에", type: "adverb" },
  "park": { en: "park", ko: "공원", type: "noun" },
  "keychain": { en: "keychain", ko: "열쇠고리", type: "noun" },
  "scam": { en: "scam", ko: "사기", type: "noun" },
  "bought": { en: "bought", ko: "샀다 (buy의 과거형)", type: "verb" },
  "fake": { en: "fake", ko: "가짜의", type: "adjective" },
  "tickets": { en: "tickets", ko: "티켓들", type: "noun" },
  "street": { en: "street", ko: "거리", type: "noun" },
  "vendor": { en: "vendor", ko: "노점상, 판매자", type: "noun" },
  "paid": { en: "paid", ko: "지불했다 (pay의 과거형)", type: "verb" },
  "wait": { en: "wait", ko: "기다리다", type: "verb" },
  "returned": { en: "returned", ko: "돌아왔다 (return의 과거형)", type: "verb" },
  "overcharged": { en: "overcharged", ko: "바가지를 쓴, 과다 청구된", type: "adjective" },
  "driver": { en: "driver", ko: "운전기사", type: "noun" },
  "refused": { en: "refused", ko: "거부했다 (refuse의 과거형)", type: "verb" },
  "meter": { en: "meter", ko: "미터기", type: "noun" },
  "picture": { en: "picture", ko: "사진, 그림", type: "noun" },
  "license": { en: "license", ko: "면허, 번호판", type: "noun" },
  "plate": { en: "plate", ko: "판, 번호판", type: "noun" },
  "photo": { en: "photo", ko: "사진", type: "noun" },
  "press": { en: "press", ko: "누르다, (고소를) 제기하다", type: "verb" },
  "charges": { en: "charges", ko: "고발, 기소", type: "noun" },
  "things": { en: "things", ko: "물건들", type: "noun" },
  "unsafe": { en: "unsafe", ko: "불안전한, 위험한", type: "adjective" },
  "escort": { en: "escort", ko: "에스코트하다, 호위하다", type: "verb" },
  "traveling": { en: "traveling", ko: "여행하는", type: "adjective" },
  "companion": { en: "companion", ko: "동행자, 동반자", type: "noun" },
  "attacked": { en: "attacked", ko: "공격받은", type: "adjective" },
  "group": { en: "group", ko: "무리, 그룹", type: "noun" },
  "teenagers": { en: "teenagers", ko: "10대들", type: "noun" },
  "threatened": { en: "threatened", ko: "위협했다 (threaten의 과거형)", type: "verb" },
  "knife": { en: "knife", ko: "칼", type: "noun" },
  "demanded": { en: "demanded", ko: "요구했다 (demand의 과거형)", type: "verb" },
  "money": { en: "money", ko: "돈", type: "noun" },
  "phones": { en: "phones", ko: "휴대폰들", type: "noun" },
  "handed": { en: "handed", ko: "건네주었다 (hand의 과거형)", type: "verb" },
  "physically": { en: "physically", ko: "신체적으로", type: "adverb" },
  "unharmed": { en: "unharmed", ko: "다치지 않은", type: "adjective" },
  "shocked": { en: "shocked", ko: "충격받은", type: "adjective" },
  "attention": { en: "attention", ko: "주의, 치료", type: "noun" },
  "ambulance": { en: "ambulance", ko: "구급차", type: "noun" },
  "sign": { en: "sign", ko: "서명하다", type: "verb" },
  "bottom": { en: "bottom", ko: "바닥, 하단", type: "noun" },
  "page": { en: "page", ko: "페이지", type: "noun" },
  "statement": { en: "statement", ko: "진술서, 성명", type: "noun" },
  "carefully": { en: "carefully", ko: "주의 깊게", type: "adverb" },
  "signing": { en: "signing", ko: "서명하는 것", type: "noun" },
  "correct": { en: "correct", ko: "맞는, 정확한", type: "adjective" },
  "exactly": { en: "exactly", ko: "정확히", type: "adverb" },
  "add": { en: "add", ko: "추가하다", type: "verb" },
  "detail": { en: "detail", ko: "세부 사항", type: "noun" },
  "scar": { en: "scar", ko: "흉터", type: "noun" },
  "left": { en: "left", ko: "왼쪽의", type: "adjective" },
  "cheek": { en: "cheek", ko: "뺨", type: "noun" },
  "baseball": { en: "baseball", ko: "야구", type: "noun" },
  "cap": { en: "cap", ko: "모자", type: "noun" },
  "dark": { en: "dark", ko: "어두운, 짙은", type: "adjective" },
  "blue": { en: "blue", ko: "파란색", type: "noun" },
  "sedan": { en: "sedan", ko: "세단 (승용차)", type: "noun" },
  "catch": { en: "catch", ko: "잡다, 포착하다", type: "verb" },
  "assistance": { en: "assistance", ko: "도움, 지원", type: "noun" },
  "appreciate": { en: "appreciate", ko: "감사하다", type: "verb" },
  "quick": { en: "quick", ko: "빠른", type: "adjective" },
  "response": { en: "response", ko: "반응, 대처", type: "noun" },
  "hope": { en: "hope", ko: "바라다, 희망하다", type: "verb" },
  "culprit": { en: "culprit", ko: "범인", type: "noun" }
};

const sentencesFile = 'src/sentences.json';
const dictionaryFile = 'src/dictionary.json';

const sentencesData = JSON.parse(fs.readFileSync(sentencesFile, 'utf8'));
const dictionaryData = JSON.parse(fs.readFileSync(dictionaryFile, 'utf8'));

if (!sentencesData.police) {
  sentencesData.police = [];
}

let addedSentences = 0;
for (const sentence of newSentences) {
  const exists = sentencesData.police.some(s => s.en === sentence.en);
  if (!exists) {
    sentencesData.police.push(sentence);
    addedSentences++;
  }
}

let addedWords = 0;
for (const [word, def] of Object.entries(newWords)) {
  if (!dictionaryData[word]) {
    dictionaryData[word] = def;
    addedWords++;
  }
}

fs.writeFileSync(sentencesFile, JSON.stringify(sentencesData, null, 2));
fs.writeFileSync(dictionaryFile, JSON.stringify(dictionaryData, null, 2));

console.log(`Added ${addedSentences} sentences and ${addedWords} words to police category.`);
