const fs = require('fs');

const newSentences = [
  { en: "I've been robbed.", ko: "강도를 당했어요.", tip: "경찰에 신고할 때 사용합니다." },
  { en: "Someone stole my wallet.", ko: "누군가 제 지갑을 훔쳐갔어요.", tip: "소매치기나 도난을 당했을 때 씁니다." },
  { en: "My passport is missing.", ko: "여권이 없어졌어요.", tip: "여권을 분실했을 때 대사관이나 경찰서에서 사용합니다." },
  { en: "Please call the police.", ko: "경찰을 불러주세요.", tip: "범죄 피해를 입었거나 위험할 때 요청합니다." },
  { en: "Where is the nearest police station?", ko: "가장 가까운 경찰서가 어디인가요?", tip: "경찰서 위치를 물어볼 때 씁니다." },
  { en: "I need to contact my embassy.", ko: "대사관에 연락해야 해요.", tip: "해외에서 심각한 문제가 생겼을 때 대사관의 도움이 필요할 때 씁니다." },
  { en: "I lost my bag on the train.", ko: "기차에 가방을 두고 내렸어요.", tip: "대중교통에서 물건을 분실했을 때 분실물 센터에 말합니다." },
  { en: "Can I use your phone?", ko: "전화기 좀 빌릴 수 있을까요?", tip: "휴대폰이 없거나 배터리가 방전되어 급히 연락해야 할 때 씁니다." },
  { en: "It's an emergency.", ko: "응급 상황입니다.", tip: "상황의 심각성을 알릴 때 사용합니다." },
  { en: "I'm bleeding heavily.", ko: "피를 많이 흘리고 있어요.", tip: "심한 출혈이 있을 때 의료진에게 알립니다." },
  { en: "He is unconscious.", ko: "그가 의식을 잃었어요.", tip: "주변 사람이 쓰러졌을 때 구조대원에게 상태를 설명합니다." },
  { en: "She is not breathing.", ko: "그녀가 숨을 쉬지 않아요.", tip: "호흡이 멈춘 위급 환자를 발견했을 때 사용합니다." },
  { en: "Is there a doctor around here?", ko: "이 근처에 의사 선생님 계신가요?", tip: "응급 환자 발생 시 주변에 의료진을 찾을 때 외칩니다." },
  { en: "I have a severe allergy.", ko: "저는 심한 알레르기가 있어요.", tip: "알레르기 반응이 나타날 때 주변에 알립니다." },
  { en: "I need my medication.", ko: "제 약이 필요해요.", tip: "지병으로 인해 급히 약을 먹어야 할 때 씁니다." },
  { en: "I think I broke my leg.", ko: "다리가 부러진 것 같아요.", tip: "골절이 의심될 때 상태를 설명합니다." },
  { en: "I feel dizzy and nauseous.", ko: "어지럽고 속이 안 좋아요.", tip: "몸 상태가 급격히 안 좋아졌을 때 증상을 말합니다." },
  { en: "My chest hurts.", ko: "가슴이 아파요.", tip: "심장 통증 등 흉통이 있을 때 즉시 알립니다." },
  { en: "I can't breathe well.", ko: "숨을 잘 못 쉬겠어요.", tip: "호흡 곤란이 올 때 증상을 설명합니다." },
  { en: "I've been in a car accident.", ko: "교통사고가 났어요.", tip: "교통사고 발생 시 경찰이나 구급대에 신고합니다." },
  { en: "The car is on fire.", ko: "차에 불이 났어요.", tip: "차량 화재 발생 시 대피하며 신고할 때 씁니다." },
  { en: "We need a tow truck.", ko: "견인차가 필요해요.", tip: "차가 고장나서 움직일 수 없을 때 요청합니다." },
  { en: "I have a flat tire.", ko: "타이어가 펑크 났어요.", tip: "타이어 문제로 주행이 불가능할 때 도움을 청합니다." },
  { en: "My car broke down.", ko: "제 차가 고장 났어요.", tip: "차량 고장으로 멈췄을 때 상황을 설명합니다." },
  { en: "I'm locked out of my room.", ko: "방에 갇혔어요. / 방 문이 잠겼어요.", tip: "호텔 등에서 키를 두고 나와 못 들어갈 때 씁니다." },
  { en: "I lost my room key.", ko: "방 열쇠를 잃어버렸어요.", tip: "호텔 프론트에 열쇠 분실을 알릴 때 사용합니다." },
  { en: "There is a fire in the building.", ko: "건물에 불이 났어요.", tip: "화재를 발견하고 주변에 알리거나 신고할 때 외칩니다." },
  { en: "Where is the emergency exit?", ko: "비상구가 어디인가요?", tip: "화재나 비상 상황 시 대피로를 찾을 때 묻습니다." },
  { en: "Please evacuate immediately.", ko: "즉시 대피하세요.", tip: "위험 상황에서 사람들을 대피시킬 때 사용합니다." },
  { en: "I smell gas.", ko: "가스 냄새가 나요.", tip: "가스 누출이 의심될 때 주변에 알리고 대피합니다." },
  { en: "The elevator is stuck.", ko: "엘리베이터가 멈췄어요.", tip: "엘리베이터에 갇혔을 때 비상벨을 누르고 말합니다." },
  { en: "I'm lost. Can you help me?", ko: "길을 잃었어요. 도와주시겠어요?", tip: "낯선 곳에서 길을 잃었을 때 도움을 청합니다." },
  { en: "I can't find my child.", ko: "제 아이를 찾을 수가 없어요.", tip: "아이를 잃어버렸을 때 경찰이나 안내원에게 알립니다." },
  { en: "What does he look like?", ko: "그는 어떻게 생겼나요?", tip: "미아 발생 시 인상착의를 물어볼 때 씁니다." },
  { en: "He is wearing a red shirt.", ko: "그는 빨간 셔츠를 입고 있어요.", tip: "잃어버린 사람의 옷차림을 설명할 때 사용합니다." },
  { en: "I've been mugged.", ko: "노상강도를 당했어요.", tip: "길에서 강도를 당했을 때 경찰에 신고합니다." },
  { en: "Someone is following me.", ko: "누군가 저를 따라오고 있어요.", tip: "미행을 당하고 있다고 느낄 때 도움을 청합니다." },
  { en: "Leave me alone!", ko: "저를 내버려 두세요!", tip: "누군가 괴롭히거나 귀찮게 할 때 단호하게 말합니다." },
  { en: "Stop, thief!", ko: "도둑 잡아라!", tip: "도둑을 발견하고 주변에 도움을 요청할 때 외칩니다." },
  { en: "I need a lawyer.", ko: "변호사가 필요해요.", tip: "법적인 문제가 생겨 변호사의 도움이 필요할 때 씁니다." },
  { en: "I want to report a crime.", ko: "범죄를 신고하고 싶습니다.", tip: "경찰서에서 범죄 사실을 알릴 때 사용합니다." },
  { en: "Did you see what happened?", ko: "무슨 일이 있었는지 보셨나요?", tip: "사고나 범죄의 목격자를 찾을 때 묻습니다." },
  { en: "I saw the whole thing.", ko: "제가 모든 것을 다 봤어요.", tip: "목격자로서 상황을 설명할 준비가 되었을 때 말합니다." },
  { en: "Can you describe the suspect?", ko: "용의자의 인상착의를 설명해 주시겠어요?", tip: "경찰이 목격자에게 범인의 모습을 물어볼 때 씁니다." },
  { en: "He ran that way.", ko: "그가 저쪽으로 도망갔어요.", tip: "범인의 도주 방향을 알려줄 때 사용합니다." },
  { en: "Please hurry!", ko: "서둘러 주세요!", tip: "구급차나 경찰의 빠른 출동을 촉구할 때 씁니다." },
  { en: "How long will it take?", ko: "얼마나 걸릴까요?", tip: "구조대나 경찰이 도착하는 데 걸리는 시간을 물어볼 때 씁니다." },
  { en: "Stay calm.", ko: "침착하세요.", tip: "당황한 사람을 안심시킬 때 말합니다." },
  { en: "Don't move.", ko: "움직이지 마세요.", tip: "부상자가 움직이면 위험할 때 경고합니다." },
  { en: "Everything will be okay.", ko: "다 괜찮아질 거예요.", tip: "응급 상황에서 환자나 피해자를 위로할 때 씁니다." },
  { en: "I'm having a heart attack.", ko: "심장마비가 온 것 같아요.", tip: "심장마비 증상이 있을 때 즉각적인 도움을 요청합니다." },
  { en: "Do you know CPR?", ko: "심폐소생술 할 줄 아시나요?", tip: "심정지 환자 발생 시 CPR 가능한 사람을 찾을 때 묻습니다." },
  { en: "Where is the automated external defibrillator?", ko: "자동심장충격기(AED)가 어디 있나요?", tip: "응급 상황에서 AED를 찾을 때 씁니다." },
  { en: "I burned my hand.", ko: "손을 데였어요.", tip: "화상을 입었을 때 상태를 알립니다." },
  { en: "I got bitten by a dog.", ko: "개에게 물렸어요.", tip: "동물에게 물려 치료가 필요할 때 상황을 설명합니다." },
  { en: "I swallowed something poisonous.", ko: "독성이 있는 것을 삼켰어요.", tip: "독극물이나 잘못된 약을 삼켰을 때 응급실에 알립니다." },
  { en: "My water broke.", ko: "양수가 터졌어요.", tip: "임산부의 출산이 임박했을 때 알립니다." },
  { en: "I'm in labor.", ko: "진통이 시작됐어요.", tip: "출산 진통이 시작되었음을 알릴 때 사용합니다." },
  { en: "I dropped my phone in the water.", ko: "휴대폰을 물에 빠뜨렸어요.", tip: "전자기기가 침수되었을 때 상황을 설명합니다." },
  { en: "My credit card was swallowed by the ATM.", ko: "ATM 기계가 제 신용카드를 삼켰어요.", tip: "해외에서 ATM 기기 오류로 카드를 잃었을 때 은행에 말합니다." },
  { en: "I need to cancel my credit card.", ko: "신용카드를 정지해야 해요.", tip: "카드 분실이나 도난 시 카드사에 연락할 때 씁니다." },
  { en: "My flight was cancelled.", ko: "제 비행기가 취소되었어요.", tip: "항공편 취소로 인해 도움이 필요할 때 항공사 직원에게 말합니다." },
  { en: "I missed my flight.", ko: "비행기를 놓쳤어요.", tip: "비행기 탑승 시간을 놓쳤을 때 대처 방법을 물어보기 위해 씁니다." },
  { en: "Where is the lost and found?", ko: "분실물 센터가 어디인가요?", tip: "공항이나 역에서 물건을 잃어버렸을 때 찾습니다." },
  { en: "I left my luggage on the bus.", ko: "버스에 짐을 두고 내렸어요.", tip: "버스에 짐을 놓고 내렸을 때 분실물 센터에 알립니다." },
  { en: "My luggage hasn't arrived.", ko: "제 수하물이 도착하지 않았어요.", tip: "공항에서 수하물을 찾지 못했을 때 수하물 센터에 신고합니다." },
  { en: "I need an interpreter.", ko: "통역사가 필요해요.", tip: "의사소통이 어려워 통역 지원이 필요할 때 요청합니다." },
  { en: "Do you speak Korean?", ko: "한국어 할 줄 아시나요?", tip: "한국어 소통이 가능한 사람을 찾을 때 묻습니다." },
  { en: "I don't understand what you're saying.", ko: "무슨 말씀이신지 이해를 못 하겠어요.", tip: "상대방의 말을 알아듣지 못했을 때 솔직하게 말합니다." },
  { en: "Please write it down.", ko: "적어 주시겠어요?", tip: "말을 알아듣기 힘들 때 글로 써달라고 요청합니다." },
  { en: "I need a painkiller.", ko: "진통제가 필요해요.", tip: "통증이 심해서 약국이나 병원에서 진통제를 찾을 때 씁니다." },
  { en: "Where is the nearest pharmacy?", ko: "가장 가까운 약국이 어디인가요?", tip: "급히 약을 사야 할 때 약국 위치를 묻습니다." },
  { en: "I have a high fever.", ko: "열이 높아요.", tip: "고열 증상을 의사나 약사에게 설명할 때 사용합니다." },
  { en: "I have food poisoning.", ko: "식중독에 걸렸어요.", tip: "음식을 잘못 먹고 배탈이 났을 때 증상을 말합니다." },
  { en: "I need a bandage.", ko: "반창고가 필요해요.", tip: "가벼운 상처가 났을 때 반창고를 찾습니다." },
  { en: "Is it safe to drink the tap water?", ko: "수돗물을 마셔도 안전한가요?", tip: "해외에서 수돗물 음용 가능 여부를 물어볼 때 씁니다." },
  { en: "I need to go to the hospital.", ko: "병원에 가야 해요.", tip: "아파서 병원 진료가 필요할 때 주변에 알립니다." },
  { en: "Can you take me to the hospital?", ko: "저를 병원으로 데려다 주실 수 있나요?", tip: "혼자 병원에 가기 힘들 때 도움을 청합니다." },
  { en: "I have travel insurance.", ko: "저는 여행자 보험이 있습니다.", tip: "병원 진료 접수 시 보험 가입 여부를 알릴 때 씁니다." },
  { en: "I need a medical certificate.", ko: "진단서가 필요해요.", tip: "보험 청구 등을 위해 진단서 발급을 요청할 때 사용합니다." },
  { en: "I'm trapped in the bathroom.", ko: "화장실에 갇혔어요.", tip: "화장실 문이 고장나서 갇혔을 때 도움을 요청합니다." },
  { en: "The toilet is overflowing.", ko: "변기 물이 넘치고 있어요.", tip: "변기가 막혀 물이 넘칠 때 수리를 요청합니다." },
  { en: "There is no hot water.", ko: "따뜻한 물이 안 나와요.", tip: "호텔 등에서 온수가 나오지 않을 때 프론트에 알립니다." },
  { en: "The power went out.", ko: "정전이 되었어요.", tip: "갑자기 전기가 나갔을 때 상황을 설명합니다." },
  { en: "I lost my contact lenses.", ko: "콘택트렌즈를 잃어버렸어요.", tip: "렌즈를 잃어버려 앞이 잘 안 보일 때 도움을 청합니다." }
];

const newWords = {
  "robbed": { en: "robbed", ko: "강도를 당한", type: "adjective" },
  "stole": { en: "stole", ko: "훔쳤다 (steal의 과거형)", type: "verb" },
  "wallet": { en: "wallet", ko: "지갑", type: "noun" },
  "missing": { en: "missing", ko: "없어진, 실종된", type: "adjective" },
  "police": { en: "police", ko: "경찰", type: "noun" },
  "station": { en: "station", ko: "서, 역", type: "noun" },
  "embassy": { en: "embassy", ko: "대사관", type: "noun" },
  "contact": { en: "contact", ko: "연락하다", type: "verb" },
  "emergency": { en: "emergency", ko: "비상 사태, 응급 상황", type: "noun" },
  "bleeding": { en: "bleeding", ko: "출혈", type: "noun" },
  "heavily": { en: "heavily", ko: "심하게, 몹시", type: "adverb" },
  "unconscious": { en: "unconscious", ko: "의식을 잃은", type: "adjective" },
  "breathing": { en: "breathing", ko: "호흡", type: "noun" },
  "severe": { en: "severe", ko: "심각한, 극심한", type: "adjective" },
  "allergy": { en: "allergy", ko: "알레르기", type: "noun" },
  "medication": { en: "medication", ko: "약물, 약", type: "noun" },
  "broke": { en: "broke", ko: "부러뜨렸다 (break의 과거형)", type: "verb" },
  "dizzy": { en: "dizzy", ko: "어지러운", type: "adjective" },
  "nauseous": { en: "nauseous", ko: "메스꺼운", type: "adjective" },
  "chest": { en: "chest", ko: "가슴", type: "noun" },
  "accident": { en: "accident", ko: "사고", type: "noun" },
  "fire": { en: "fire", ko: "화재, 불", type: "noun" },
  "tow": { en: "tow", ko: "견인하다", type: "verb" },
  "truck": { en: "truck", ko: "트럭", type: "noun" },
  "flat": { en: "flat", ko: "평평한, 펑크 난", type: "adjective" },
  "tire": { en: "tire", ko: "타이어", type: "noun" },
  "down": { en: "down", ko: "고장 난, 작동하지 않는", type: "adjective" },
  "locked": { en: "locked", ko: "잠긴", type: "adjective" },
  "key": { en: "key", ko: "열쇠", type: "noun" },
  "building": { en: "building", ko: "건물", type: "noun" },
  "exit": { en: "exit", ko: "출구", type: "noun" },
  "evacuate": { en: "evacuate", ko: "대피하다", type: "verb" },
  "immediately": { en: "immediately", ko: "즉시", type: "adverb" },
  "smell": { en: "smell", ko: "냄새를 맡다", type: "verb" },
  "gas": { en: "gas", ko: "가스", type: "noun" },
  "elevator": { en: "elevator", ko: "엘리베이터", type: "noun" },
  "stuck": { en: "stuck", ko: "갇힌, 꼼짝 못하는", type: "adjective" },
  "lost": { en: "lost", ko: "길을 잃은, 분실된", type: "adjective" },
  "child": { en: "child", ko: "아이", type: "noun" },
  "look": { en: "look", ko: "보이다, 생기다", type: "verb" },
  "wearing": { en: "wearing", ko: "입고 있는", type: "adjective" },
  "shirt": { en: "shirt", ko: "셔츠", type: "noun" },
  "mugged": { en: "mugged", ko: "노상강도를 당한", type: "adjective" },
  "following": { en: "following", ko: "따라오는", type: "adjective" },
  "alone": { en: "alone", ko: "혼자", type: "adjective" },
  "thief": { en: "thief", ko: "도둑", type: "noun" },
  "lawyer": { en: "lawyer", ko: "변호사", type: "noun" },
  "report": { en: "report", ko: "신고하다, 보고하다", type: "verb" },
  "crime": { en: "crime", ko: "범죄", type: "noun" },
  "happened": { en: "happened", ko: "일어났다 (happen의 과거형)", type: "verb" },
  "whole": { en: "whole", ko: "전체의, 모든", type: "adjective" },
  "thing": { en: "thing", ko: "것, 일", type: "noun" },
  "describe": { en: "describe", ko: "묘사하다, 설명하다", type: "verb" },
  "suspect": { en: "suspect", ko: "용의자", type: "noun" },
  "ran": { en: "ran", ko: "달렸다 (run의 과거형)", type: "verb" },
  "way": { en: "way", ko: "길, 방향", type: "noun" },
  "hurry": { en: "hurry", ko: "서두르다", type: "verb" },
  "long": { en: "long", ko: "오래, 긴", type: "adjective" },
  "take": { en: "take", ko: "걸리다 (시간이)", type: "verb" },
  "calm": { en: "calm", ko: "침착한", type: "adjective" },
  "move": { en: "move", ko: "움직이다", type: "verb" },
  "okay": { en: "okay", ko: "괜찮은", type: "adjective" },
  "heart": { en: "heart", ko: "심장", type: "noun" },
  "attack": { en: "attack", ko: "발작, 공격", type: "noun" },
  "automated": { en: "automated", ko: "자동화된", type: "adjective" },
  "external": { en: "external", ko: "외부의", type: "adjective" },
  "defibrillator": { en: "defibrillator", ko: "제세동기", type: "noun" },
  "burned": { en: "burned", ko: "데인, 화상을 입은", type: "adjective" },
  "hand": { en: "hand", ko: "손", type: "noun" },
  "bitten": { en: "bitten", ko: "물린", type: "adjective" },
  "dog": { en: "dog", ko: "개", type: "noun" },
  "swallowed": { en: "swallowed", ko: "삼켰다 (swallow의 과거형)", type: "verb" },
  "poisonous": { en: "poisonous", ko: "독성이 있는", type: "adjective" },
  "water": { en: "water", ko: "물, 양수", type: "noun" },
  "labor": { en: "labor", ko: "진통, 분만", type: "noun" },
  "dropped": { en: "dropped", ko: "떨어뜨렸다 (drop의 과거형)", type: "verb" },
  "credit": { en: "credit", ko: "신용", type: "noun" },
  "card": { en: "card", ko: "카드", type: "noun" },
  "cancel": { en: "cancel", ko: "취소하다, 정지하다", type: "verb" },
  "flight": { en: "flight", ko: "비행기, 항공편", type: "noun" },
  "cancelled": { en: "cancelled", ko: "취소된", type: "adjective" },
  "missed": { en: "missed", ko: "놓친", type: "adjective" },
  "found": { en: "found", ko: "찾은, 습득물", type: "noun" },
  "left": { en: "left", ko: "두고 왔다 (leave의 과거형)", type: "verb" },
  "luggage": { en: "luggage", ko: "수하물, 짐", type: "noun" },
  "bus": { en: "bus", ko: "버스", type: "noun" },
  "arrived": { en: "arrived", ko: "도착했다 (arrive의 과거형)", type: "verb" },
  "interpreter": { en: "interpreter", ko: "통역사", type: "noun" },
  "speak": { en: "speak", ko: "말하다", type: "verb" },
  "understand": { en: "understand", ko: "이해하다", type: "verb" },
  "saying": { en: "saying", ko: "말하는 것", type: "noun" },
  "write": { en: "write", ko: "쓰다, 적다", type: "verb" },
  "painkiller": { en: "painkiller", ko: "진통제", type: "noun" },
  "pharmacy": { en: "pharmacy", ko: "약국", type: "noun" },
  "high": { en: "high", ko: "높은", type: "adjective" },
  "fever": { en: "fever", ko: "열", type: "noun" },
  "food": { en: "food", ko: "음식", type: "noun" },
  "poisoning": { en: "poisoning", ko: "중독", type: "noun" },
  "bandage": { en: "bandage", ko: "반창고, 붕대", type: "noun" },
  "safe": { en: "safe", ko: "안전한", type: "adjective" },
  "drink": { en: "drink", ko: "마시다", type: "verb" },
  "tap": { en: "tap", ko: "수도꼭지", type: "noun" },
  "hospital": { en: "hospital", ko: "병원", type: "noun" },
  "travel": { en: "travel", ko: "여행", type: "noun" },
  "insurance": { en: "insurance", ko: "보험", type: "noun" },
  "medical": { en: "medical", ko: "의료의", type: "adjective" },
  "certificate": { en: "certificate", ko: "증명서, 진단서", type: "noun" },
  "trapped": { en: "trapped", ko: "갇힌", type: "adjective" },
  "bathroom": { en: "bathroom", ko: "화장실", type: "noun" },
  "toilet": { en: "toilet", ko: "변기", type: "noun" },
  "overflowing": { en: "overflowing", ko: "넘치는", type: "adjective" },
  "hot": { en: "hot", ko: "뜨거운, 따뜻한", type: "adjective" },
  "power": { en: "power", ko: "전력, 전기", type: "noun" },
  "out": { en: "out", ko: "나간, 끊긴", type: "adjective" },
  "contact": { en: "contact", ko: "콘택트(렌즈)", type: "noun" },
  "lenses": { en: "lenses", ko: "렌즈들", type: "noun" }
};

const sentencesFile = 'src/sentences.json';
const dictionaryFile = 'src/dictionary.json';

const sentencesData = JSON.parse(fs.readFileSync(sentencesFile, 'utf8'));
const dictionaryData = JSON.parse(fs.readFileSync(dictionaryFile, 'utf8'));

if (!sentencesData.emergency) {
  sentencesData.emergency = [];
}

let addedSentences = 0;
for (const sentence of newSentences) {
  const exists = sentencesData.emergency.some(s => s.en === sentence.en);
  if (!exists) {
    sentencesData.emergency.push(sentence);
    addedSentences++;
  }
}

let addedWords = 0;
for (const [word, def] of Object.entries(newWords)) {
  if (!dictionaryData[word]) {
    dictionaryData[word] = def;
    addedWords++;
  }
}

fs.writeFileSync(sentencesFile, JSON.stringify(sentencesData, null, 2));
fs.writeFileSync(dictionaryFile, JSON.stringify(dictionaryData, null, 2));

console.log(`Added ${addedSentences} sentences and ${addedWords} words to emergency category.`);
