const fs = require('fs');

const newSentences = [
  { en: "I'd like to see a doctor, please.", ko: "의사 선생님께 진료를 받고 싶습니다.", tip: "병원 접수처에서 진료를 요청할 때 사용합니다." },
  { en: "Do I need to make an appointment?", ko: "예약을 해야 하나요?", tip: "예약 필수 여부를 물어볼 때 씁니다." },
  { en: "I have an appointment with Dr. Smith at 10 AM.", ko: "오전 10시에 스미스 선생님과 예약이 되어 있습니다.", tip: "예약된 진료를 확인받을 때 사용합니다." },
  { en: "This is my first time here.", ko: "여기는 처음입니다.", tip: "초진임을 알릴 때 씁니다." },
  { en: "Could you fill out this form, please?", ko: "이 양식을 작성해 주시겠어요?", tip: "접수처에서 문진표나 개인정보 작성을 요청할 때 듣는 말입니다." },
  { en: "Do you accept foreign travel insurance?", ko: "해외 여행자 보험이 적용되나요?", tip: "여행자 보험 처리 가능 여부를 물어볼 때 씁니다." },
  { en: "I don't have health insurance.", ko: "저는 건강 보험이 없습니다.", tip: "보험이 없음을 알릴 때 사용합니다." },
  { en: "How much is the consultation fee?", ko: "진료비가 얼마인가요?", tip: "기본 진료비를 미리 확인할 때 묻습니다." },
  { en: "Where is the waiting room?", ko: "대기실이 어디인가요?", tip: "접수 후 대기 장소를 찾을 때 씁니다." },
  { en: "How long is the wait?", ko: "얼마나 기다려야 하나요?", tip: "대기 시간을 물어볼 때 사용합니다." },
  { en: "What seems to be the problem today?", ko: "오늘 어디가 불편해서 오셨나요?", tip: "의사가 증상을 물어볼 때 하는 말입니다." },
  { en: "I have a terrible headache.", ko: "머리가 너무 아파요.", tip: "심한 두통을 호소할 때 씁니다." },
  { en: "My stomach hurts really badly.", ko: "배가 너무 아파요.", tip: "심한 복통을 설명할 때 사용합니다." },
  { en: "I have a sore throat and a cough.", ko: "목이 아프고 기침이 나요.", tip: "감기나 인후염 증상을 말할 때 씁니다." },
  { en: "I've been feeling dizzy since this morning.", ko: "오늘 아침부터 어지러워요.", tip: "어지럼증이 시작된 시점과 함께 증상을 말합니다." },
  { en: "I have a high fever and chills.", ko: "고열이 나고 오한이 있어요.", tip: "열과 함께 몸이 떨리는 증상을 설명합니다." },
  { en: "My nose is runny and stuffed up.", ko: "콧물이 나고 코가 막혀요.", tip: "비염이나 코감기 증상을 말할 때 씁니다." },
  { en: "I've been vomiting all night.", ko: "밤새 토했어요.", tip: "구토 증상을 설명할 때 사용합니다." },
  { en: "I have severe diarrhea.", ko: "심한 설사를 해요.", tip: "설사 증상을 의사에게 알릴 때 씁니다." },
  { en: "I feel nauseous.", ko: "속이 메스꺼워요.", tip: "토할 것 같은 느낌을 설명할 때 사용합니다." },
  { en: "I have a sharp pain in my chest.", ko: "가슴에 찌르는 듯한 통증이 있어요.", tip: "흉통의 양상을 구체적으로 설명할 때 씁니다." },
  { en: "My lower back is killing me.", ko: "허리가 끊어질 듯이 아파요.", tip: "극심한 요통을 과장하여 표현할 때 씁니다." },
  { en: "I sprained my ankle.", ko: "발목을 삐었어요.", tip: "발목 염좌를 설명할 때 사용합니다." },
  { en: "I think I broke my arm.", ko: "팔이 부러진 것 같아요.", tip: "골절이 의심될 때 증상을 말합니다." },
  { en: "I have a rash on my arm.", ko: "팔에 발진이 생겼어요.", tip: "피부에 붉은 반점이나 발진이 났을 때 씁니다." },
  { en: "My skin is very itchy.", ko: "피부가 너무 가려워요.", tip: "가려움증을 호소할 때 사용합니다." },
  { en: "My eyes are red and swollen.", ko: "눈이 충혈되고 부었어요.", tip: "안과 질환이나 알레르기 증상을 설명할 때 씁니다." },
  { en: "I have a toothache.", ko: "치통이 있어요.", tip: "이가 아플 때 치과에서 사용합니다." },
  { en: "I have a terrible earache.", ko: "귀가 너무 아파요.", tip: "귀 통증을 호소할 때 씁니다." },
  { en: "I can't stop sneezing.", ko: "재채기가 멈추지 않아요.", tip: "알레르기나 감기로 인한 잦은 재채기를 말합니다." },
  { en: "I feel very weak and tired.", ko: "몸에 기운이 없고 너무 피곤해요.", tip: "전신 무력감과 피로를 설명할 때 씁니다." },
  { en: "I have a loss of appetite.", ko: "식욕이 없어요.", tip: "입맛이 없음을 의사에게 알릴 때 사용합니다." },
  { en: "I can't sleep well at night.", ko: "밤에 잠을 잘 못 자요.", tip: "불면증 증상을 설명할 때 씁니다." },
  { en: "It hurts right here.", ko: "바로 여기가 아파요.", tip: "아픈 부위를 직접 가리키며 말할 때 사용합니다." },
  { en: "It hurts when I press here.", ko: "여기를 누르면 아파요.", tip: "압통이 있음을 설명할 때 씁니다." },
  { en: "The pain is getting worse.", ko: "통증이 점점 심해져요.", tip: "증상이 악화되고 있음을 알릴 때 사용합니다." },
  { en: "It's a dull, throbbing ache.", ko: "둔하고 욱신거리는 통증이에요.", tip: "통증의 느낌을 자세히 묘사할 때 씁니다." },
  { en: "When did the symptoms start?", ko: "증상이 언제 시작되었나요?", tip: "의사가 발병 시기를 물어볼 때 하는 말입니다." },
  { en: "It started two days ago.", ko: "이틀 전에 시작되었어요.", tip: "증상 시작 시점을 대답할 때 씁니다." },
  { en: "Have you taken any medicine for this?", ko: "이 증상 때문에 약을 드신 적이 있나요?", tip: "의사가 자가 투약 여부를 물어볼 때 씁니다." },
  { en: "I took some painkillers yesterday.", ko: "어제 진통제를 좀 먹었어요.", tip: "복용한 약을 의사에게 알릴 때 사용합니다." },
  { en: "Are you allergic to any medications?", ko: "약물 알레르기가 있나요?", tip: "의사나 약사가 알레르기 여부를 확인할 때 묻습니다." },
  { en: "I am allergic to penicillin.", ko: "저는 페니실린 알레르기가 있어요.", tip: "특정 약물 알레르기를 알릴 때 매우 중요합니다." },
  { en: "I don't have any known allergies.", ko: "알려진 알레르기는 없습니다.", 기: "알레르기가 없다고 대답할 때 씁니다." },
  { en: "Are you currently taking any medication?", ko: "현재 복용 중인 약이 있나요?", tip: "의사가 현재 투약 상태를 물어볼 때 씁니다." },
  { en: "I take blood pressure medicine daily.", ko: "매일 혈압약을 먹고 있어요.", tip: "지병으로 먹는 약을 설명할 때 사용합니다." },
  { en: "Is there any chance you might be pregnant?", ko: "임신 가능성이 있나요?", tip: "X-ray 촬영이나 약 처방 전 의사가 묻는 질문입니다." },
  { en: "I am three months pregnant.", ko: "임신 3개월입니다.", tip: "임신 상태임을 알릴 때 반드시 말해야 합니다." },
  { en: "I am breastfeeding.", ko: "모유 수유 중입니다.", tip: "수유 중임을 알려 안전한 약을 처방받기 위해 씁니다." },
  { en: "I have a history of asthma.", ko: "천식 병력이 있습니다.", tip: "과거 병력을 의사에게 알릴 때 사용합니다." },
  { en: "I have diabetes.", ko: "저는 당뇨가 있습니다.", tip: "당뇨병이 있음을 알릴 때 씁니다." },
  { en: "Let me check your blood pressure.", ko: "혈압을 재보겠습니다.", tip: "간호사나 의사가 혈압 측정을 안내할 때 씁니다." },
  { en: "Please step on the scale.", ko: "체중계에 올라가 주세요.", tip: "몸무게를 잴 때 듣는 말입니다." },
  { en: "Open your mouth and say ah.", ko: "입을 벌리고 아 해보세요.", tip: "목 안을 진찰할 때 의사가 하는 말입니다." },
  { en: "Take a deep breath and hold it.", ko: "숨을 깊게 들이마시고 참으세요.", tip: "청진이나 흉부 X-ray 촬영 시 듣는 말입니다." },
  { en: "We need to run some blood tests.", ko: "혈액 검사를 좀 해야겠습니다.", tip: "의사가 피검사를 지시할 때 씁니다." },
  { en: "You need to get an X-ray.", ko: "엑스레이를 찍어보셔야 합니다.", tip: "방사선 촬영이 필요할 때 듣는 말입니다." },
  { en: "We need a urine sample.", ko: "소변 샘플이 필요합니다.", tip: "소변 검사를 안내받을 때 씁니다." },
  { en: "It looks like a viral infection.", ko: "바이러스 감염인 것 같습니다.", tip: "의사가 진단 결과를 말해줄 때 씁니다." },
  { en: "You have food poisoning.", ko: "식중독입니다.", tip: "식중독 진단을 받았을 때 듣는 말입니다." },
  { en: "It's just a common cold.", ko: "그냥 단순한 감기입니다.", tip: "가벼운 감기라는 진단을 받을 때 씁니다." },
  { en: "You need to get some rest.", ko: "휴식을 좀 취하셔야 합니다.", tip: "의사가 안정을 권고할 때 하는 말입니다." },
  { en: "Drink plenty of fluids.", ko: "수분을 충분히 섭취하세요.", tip: "물을 많이 마시라는 의사의 조언입니다." },
  { en: "You should avoid spicy food.", ko: "매운 음식은 피하셔야 합니다.", tip: "위장 질환 시 식단 주의사항을 들을 때 씁니다." },
  { en: "I'm going to prescribe some antibiotics.", ko: "항생제를 처방해 드리겠습니다.", tip: "의사가 약 처방 계획을 말할 때 씁니다." },
  { en: "You need to take this for five days.", ko: "이 약을 5일 동안 드셔야 합니다.", tip: "투약 기간을 안내받을 때 듣는 말입니다." },
  { en: "Do I need to come back?", ko: "다시 와야 하나요?", tip: "재진이 필요한지 물어볼 때 씁니다." },
  { en: "Come back if it doesn't get better.", ko: "나아지지 않으면 다시 오세요.", tip: "경과를 지켜보자는 의사의 말입니다." },
  { en: "I need a medical certificate for my insurance.", ko: "보험 청구용 진단서가 필요합니다.", tip: "보험사에 제출할 서류를 요청할 때 씁니다." },
  { en: "Can I get a copy of my medical records?", ko: "진료 기록 사본을 받을 수 있을까요?", tip: "의무 기록을 복사해 달라고 할 때 사용합니다." },
  { en: "Can I get a receipt, please?", ko: "영수증 좀 주시겠어요?", tip: "수납 후 영수증 발급을 요청할 때 씁니다." },
  { en: "Where is the nearest pharmacy?", ko: "가장 가까운 약국이 어디인가요?", tip: "처방전을 가지고 약국을 찾을 때 묻습니다." },
  { en: "I'd like to fill this prescription, please.", ko: "이 처방전대로 약을 조제해 주세요.", tip: "약국에 처방전을 제출하며 하는 말입니다." },
  { en: "How long will it take to prepare?", ko: "약이 나오는 데 얼마나 걸리나요?", tip: "조제 대기 시간을 물어볼 때 씁니다." },
  { en: "It will be ready in about ten minutes.", ko: "약 10분 정도 걸립니다.", tip: "약사가 대기 시간을 알려줄 때 하는 말입니다." },
  { en: "Do you have any over-the-counter medicine for a cold?", ko: "처방전 없이 살 수 있는 감기약 있나요?", tip: "일반 의약품을 찾을 때 씁니다." },
  { en: "I need something for a headache.", ko: "두통약 좀 주세요.", tip: "증상을 말하고 약을 추천받을 때 사용합니다." },
  { en: "Do you have anything for motion sickness?", ko: "멀미약 있나요?", tip: "멀미약을 찾을 때 씁니다." },
  { en: "I need some band-aids and antiseptic.", ko: "반창고와 소독약이 필요해요.", tip: "상처 치료용품을 살 때 사용합니다." },
  { en: "Do you have any digestive medicine?", ko: "소화제 있나요?", tip: "소화가 안 될 때 소화제를 찾으며 묻습니다." },
  { en: "I need eye drops for dry eyes.", ko: "안구 건조증용 안약이 필요해요.", tip: "인공눈물이나 안약을 살 때 씁니다." },
  { en: "Do you have an ointment for burns?", ko: "화상 연고 있나요?", tip: "데였을 때 바를 연고를 찾을 때 사용합니다." },
  { en: "I need a thermometer.", ko: "체온계가 필요해요.", tip: "열을 재기 위해 체온계를 살 때 씁니다." },
  { en: "How should I take this medicine?", ko: "이 약은 어떻게 먹어야 하나요?", tip: "복용법을 약사에게 물어볼 때 씁니다." },
  { en: "Take one pill three times a day.", ko: "하루 세 번 한 알씩 드세요.", tip: "가장 일반적인 복용 지시사항입니다." },
  { en: "Take this thirty minutes after meals.", ko: "식후 30분에 드세요.", tip: "식후 복용을 안내받을 때 듣는 말입니다." },
  { en: "Take this on an empty stomach.", ko: "빈속에 드세요.", tip: "식전 복용을 안내받을 때 듣는 말입니다." },
  { en: "Take this before you go to bed.", ko: "취침 전에 드세요.", tip: "수면제나 특정 약의 취침 전 복용 안내입니다." },
  { en: "Does this medicine have any side effects?", ko: "이 약에 부작용이 있나요?", tip: "약의 부작용을 미리 확인할 때 묻습니다." },
  { en: "This might make you feel drowsy.", ko: "이 약을 먹으면 졸릴 수 있습니다.", tip: "졸음 유발 부작용을 경고받을 때 듣습니다." },
  { en: "Do not drink alcohol while taking this.", ko: "이 약을 드시는 동안에는 술을 드시면 안 됩니다.", tip: "음주 금지 주의사항을 들을 때 씁니다." },
  { en: "Can I take this with other medications?", ko: "다른 약과 함께 먹어도 되나요?", tip: "약물 병용 금기가 있는지 확인할 때 묻습니다." },
  { en: "Is this safe for children?", ko: "아이들이 먹어도 안전한가요?", tip: "어린이 복용 가능 여부를 물어볼 때 씁니다." },
  { en: "What is the dosage for a ten-year-old?", ko: "10살 아이의 복용량은 어떻게 되나요?", tip: "연령에 맞는 복용량을 확인할 때 사용합니다." },
  { en: "I need a refill for my prescription.", ko: "처방전 약을 리필하고 싶어요.", tip: "장기 복용 약을 다시 타러 갈 때 씁니다." },
  { en: "My prescription has expired.", ko: "제 처방전 기한이 만료되었어요.", tip: "처방전 유효기간이 지났음을 알릴 때 씁니다." },
  { en: "Do you sell contact lens solution?", ko: "콘택트렌즈 세척액 파나요?", tip: "렌즈 세척액을 약국에서 찾을 때 묻습니다." },
  { en: "I need some vitamin C supplements.", ko: "비타민 C 영양제가 필요해요.", tip: "영양제를 구매할 때 사용합니다." },
  { en: "Do you have any insect repellent?", ko: "벌레 기피제 있나요?", tip: "모기약 등 벌레 퇴치제를 찾을 때 씁니다." },
  { en: "Thank you for your help, doctor.", ko: "도와주셔서 감사합니다, 선생님.", tip: "진료를 마치고 의사에게 인사할 때 씁니다." }
];

const newWords = {
  "appointment": { en: "appointment", ko: "예약", type: "noun" },
  "form": { en: "form", ko: "양식, 서식", type: "noun" },
  "insurance": { en: "insurance", ko: "보험", type: "noun" },
  "consultation": { en: "consultation", ko: "상담, 진찰", type: "noun" },
  "fee": { en: "fee", ko: "요금, 수수료", type: "noun" },
  "waiting": { en: "waiting", ko: "기다림, 대기", type: "noun" },
  "problem": { en: "problem", ko: "문제, 질환", type: "noun" },
  "terrible": { en: "terrible", ko: "끔찍한, 심한", type: "adjective" },
  "headache": { en: "headache", ko: "두통", type: "noun" },
  "stomachache": { en: "stomachache", ko: "복통", type: "noun" },
  "sore": { en: "sore", ko: "아픈, 따가운", type: "adjective" },
  "throat": { en: "throat", ko: "목구멍", type: "noun" },
  "cough": { en: "cough", ko: "기침", type: "noun" },
  "dizzy": { en: "dizzy", ko: "어지러운", type: "adjective" },
  "fever": { en: "fever", ko: "열", type: "noun" },
  "chills": { en: "chills", ko: "오한", type: "noun" },
  "runny": { en: "runny", ko: "흐르는", type: "adjective" },
  "stuffed": { en: "stuffed", ko: "막힌", type: "adjective" },
  "vomiting": { en: "vomiting", ko: "구토", type: "noun" },
  "diarrhea": { en: "diarrhea", ko: "설사", type: "noun" },
  "nauseous": { en: "nauseous", ko: "메스꺼운", type: "adjective" },
  "sharp": { en: "sharp", ko: "날카로운, 찌르는 듯한", type: "adjective" },
  "pain": { en: "pain", ko: "통증", type: "noun" },
  "chest": { en: "chest", ko: "가슴", type: "noun" },
  "lower": { en: "lower", ko: "아래의", type: "adjective" },
  "back": { en: "back", ko: "등, 허리", type: "noun" },
  "killing": { en: "killing", ko: "죽일 듯이 아픈", type: "adjective" },
  "sprained": { en: "sprained", ko: "삔", type: "adjective" },
  "ankle": { en: "ankle", ko: "발목", type: "noun" },
  "broke": { en: "broke", ko: "부러뜨렸다", type: "verb" },
  "arm": { en: "arm", ko: "팔", type: "noun" },
  "rash": { en: "rash", ko: "발진", type: "noun" },
  "skin": { en: "skin", ko: "피부", type: "noun" },
  "itchy": { en: "itchy", ko: "가려운", type: "adjective" },
  "swollen": { en: "swollen", ko: "부어오른", type: "adjective" },
  "toothache": { en: "toothache", ko: "치통", type: "noun" },
  "earache": { en: "earache", ko: "귀통증", type: "noun" },
  "sneezing": { en: "sneezing", ko: "재채기", type: "noun" },
  "weak": { en: "weak", ko: "약한, 기운 없는", type: "adjective" },
  "tired": { en: "tired", ko: "피곤한", type: "adjective" },
  "appetite": { en: "appetite", ko: "식욕", type: "noun" },
  "sleep": { en: "sleep", ko: "잠, 수면", type: "noun" },
  "press": { en: "press", ko: "누르다", type: "verb" },
  "worse": { en: "worse", ko: "더 나쁜, 악화된", type: "adjective" },
  "dull": { en: "dull", ko: "둔한", type: "adjective" },
  "throbbing": { en: "throbbing", ko: "욱신거리는", type: "adjective" },
  "ache": { en: "ache", ko: "아픔, 통증", type: "noun" },
  "symptoms": { en: "symptoms", ko: "증상들", type: "noun" },
  "medicine": { en: "medicine", ko: "약", type: "noun" },
  "painkillers": { en: "painkillers", ko: "진통제", type: "noun" },
  "allergic": { en: "allergic", ko: "알레르기가 있는", type: "adjective" },
  "penicillin": { en: "penicillin", ko: "페니실린", type: "noun" },
  "allergies": { en: "allergies", ko: "알레르기들", type: "noun" },
  "currently": { en: "currently", ko: "현재", type: "adverb" },
  "daily": { en: "daily", ko: "매일", type: "adverb" },
  "pregnant": { en: "pregnant", ko: "임신한", type: "adjective" },
  "breastfeeding": { en: "breastfeeding", ko: "모유 수유 중인", type: "adjective" },
  "history": { en: "history", ko: "병력, 역사", type: "noun" },
  "asthma": { en: "asthma", ko: "천식", type: "noun" },
  "diabetes": { en: "diabetes", ko: "당뇨병", type: "noun" },
  "blood": { en: "blood", ko: "피, 혈액", type: "noun" },
  "pressure": { en: "pressure", ko: "압력, 혈압", type: "noun" },
  "scale": { en: "scale", ko: "체중계, 저울", type: "noun" },
  "mouth": { en: "mouth", ko: "입", type: "noun" },
  "breath": { en: "breath", ko: "숨, 호흡", type: "noun" },
  "hold": { en: "hold", ko: "참다, 잡다", type: "verb" },
  "tests": { en: "tests", ko: "검사들", type: "noun" },
  "urine": { en: "urine", ko: "소변", type: "noun" },
  "sample": { en: "sample", ko: "샘플, 견본", type: "noun" },
  "viral": { en: "viral", ko: "바이러스성의", type: "adjective" },
  "infection": { en: "infection", ko: "감염", type: "noun" },
  "common": { en: "common", ko: "흔한, 일반적인", type: "adjective" },
  "cold": { en: "cold", ko: "감기, 추운", type: "noun" },
  "rest": { en: "rest", ko: "휴식", type: "noun" },
  "plenty": { en: "plenty", ko: "충분한, 많은", type: "adjective" },
  "fluids": { en: "fluids", ko: "수분, 액체", type: "noun" },
  "avoid": { en: "avoid", ko: "피하다", type: "verb" },
  "spicy": { en: "spicy", ko: "매운", type: "adjective" },
  "prescribe": { en: "prescribe", ko: "처방하다", type: "verb" },
  "antibiotics": { en: "antibiotics", ko: "항생제", type: "noun" },
  "better": { en: "better", ko: "더 나은", type: "adjective" },
  "certificate": { en: "certificate", ko: "증명서", type: "noun" },
  "records": { en: "records", ko: "기록들", type: "noun" },
  "receipt": { en: "receipt", ko: "영수증", type: "noun" },
  "nearest": { en: "nearest", ko: "가장 가까운", type: "adjective" },
  "pharmacy": { en: "pharmacy", ko: "약국", type: "noun" },
  "prescription": { en: "prescription", ko: "처방전", type: "noun" },
  "prepare": { en: "prepare", ko: "준비하다, 조제하다", type: "verb" },
  "ready": { en: "ready", ko: "준비된", type: "adjective" },
  "over-the-counter": { en: "over-the-counter", ko: "처방전 없이 살 수 있는", type: "adjective" },
  "motion": { en: "motion", ko: "움직임, 멀미", type: "noun" },
  "sickness": { en: "sickness", ko: "병, 멀미", type: "noun" },
  "band-aids": { en: "band-aids", ko: "반창고", type: "noun" },
  "antiseptic": { en: "antiseptic", ko: "소독제", type: "noun" },
  "digestive": { en: "digestive", ko: "소화의", type: "adjective" },
  "drops": { en: "drops", ko: "점안액, 방울", type: "noun" },
  "dry": { en: "dry", ko: "건조한", type: "adjective" },
  "ointment": { en: "ointment", ko: "연고", type: "noun" },
  "burns": { en: "burns", ko: "화상", type: "noun" },
  "thermometer": { en: "thermometer", ko: "체온계", type: "noun" },
  "pill": { en: "pill", ko: "알약", type: "noun" },
  "meals": { en: "meals", ko: "식사", type: "noun" },
  "empty": { en: "empty", ko: "빈", type: "adjective" },
  "stomach": { en: "stomach", ko: "위, 배", type: "noun" },
  "bed": { en: "bed", ko: "침대", type: "noun" },
  "side": { en: "side", ko: "부(작용), 옆", type: "noun" },
  "effects": { en: "effects", ko: "효과, 영향", type: "noun" },
  "drowsy": { en: "drowsy", ko: "졸린", type: "adjective" },
  "alcohol": { en: "alcohol", ko: "알코올, 술", type: "noun" },
  "safe": { en: "safe", ko: "안전한", type: "adjective" },
  "children": { en: "children", ko: "아이들", type: "noun" },
  "dosage": { en: "dosage", ko: "복용량", type: "noun" },
  "refill": { en: "refill", ko: "리필, 재조제", type: "noun" },
  "expired": { en: "expired", ko: "만료된", type: "adjective" },
  "sell": { en: "sell", ko: "팔다", type: "verb" },
  "contact": { en: "contact", ko: "콘택트(렌즈), 연락", type: "noun" },
  "lens": { en: "lens", ko: "렌즈", type: "noun" },
  "solution": { en: "solution", ko: "용액, 해결책", type: "noun" },
  "vitamin": { en: "vitamin", ko: "비타민", type: "noun" },
  "supplements": { en: "supplements", ko: "보충제, 영양제", type: "noun" },
  "insect": { en: "insect", ko: "곤충, 벌레", type: "noun" },
  "repellent": { en: "repellent", ko: "기피제, 퇴치제", type: "noun" }
};

const sentencesFile = 'src/sentences.json';
const dictionaryFile = 'src/dictionary.json';

const sentencesData = JSON.parse(fs.readFileSync(sentencesFile, 'utf8'));
const dictionaryData = JSON.parse(fs.readFileSync(dictionaryFile, 'utf8'));

if (!sentencesData.hospital) {
  sentencesData.hospital = [];
}

let addedSentences = 0;
for (const sentence of newSentences) {
  const exists = sentencesData.hospital.some(s => s.en === sentence.en);
  if (!exists) {
    sentencesData.hospital.push(sentence);
    addedSentences++;
  }
}

let addedWords = 0;
for (const [word, def] of Object.entries(newWords)) {
  if (!dictionaryData[word]) {
    dictionaryData[word] = def;
    addedWords++;
  }
}

fs.writeFileSync(sentencesFile, JSON.stringify(sentencesData, null, 2));
fs.writeFileSync(dictionaryFile, JSON.stringify(dictionaryData, null, 2));

console.log(`Added ${addedSentences} sentences and ${addedWords} words to hospital category.`);
