const fs = require('fs');

const newSentences = [
  { en: "Excuse me, where is the nearest subway station?", ko: "실례합니다, 가장 가까운 지하철역이 어디인가요?", tip: "길을 물어볼 때 가장 흔하게 쓰는 표현입니다." },
  { en: "How do I get to the museum from here?", ko: "여기서 박물관까지 어떻게 가나요?", tip: "특정 장소로 가는 방법을 물어볼 때 씁니다." },
  { en: "Is there a bus stop near here?", ko: "이 근처에 버스 정류장이 있나요?", tip: "가까운 대중교통 이용 장소를 찾을 때 묻습니다." },
  { en: "I'm looking for this address.", ko: "이 주소를 찾고 있어요.", tip: "주소가 적힌 종이나 스마트폰을 보여주며 묻습니다." },
  { en: "Can you show me on the map?", ko: "지도에서 보여주실 수 있나요?", tip: "지도를 펴고 위치를 확인받고 싶을 때 씁니다." },
  { en: "Am I headed the right way to the station?", ko: "역으로 가는 방향이 맞나요?", tip: "가고 있는 방향이 맞는지 확인할 때 묻습니다." },
  { en: "Go straight for two blocks.", ko: "두 블록 직진하세요.", tip: "직진 방향을 안내받을 때 듣는 말입니다." },
  { en: "Turn left at the next intersection.", ko: "다음 교차로에서 왼쪽으로 도세요.", tip: "좌회전 방향을 안내받을 때 듣는 말입니다." },
  { en: "Turn right at the traffic light.", ko: "신호등에서 오른쪽으로 도세요.", tip: "우회전 방향을 안내받을 때 듣는 말입니다." },
  { en: "It's on your right.", ko: "오른쪽에 있습니다.", tip: "목적지가 오른편에 있음을 알릴 때 씁니다." },
  { en: "It's on your left.", ko: "왼쪽에 있습니다.", tip: "목적지가 왼편에 있음을 알릴 때 씁니다." },
  { en: "It's across the street from the bank.", ko: "은행 건너편에 있어요.", tip: "건너편 위치를 설명할 때 사용합니다." },
  { en: "It's next to the post office.", ko: "우체국 옆에 있어요.", tip: "바로 옆 건물을 기준으로 위치를 설명할 때 씁니다." },
  { en: "It's behind the tall building.", ko: "높은 건물 뒤에 있어요.", tip: "건물 뒤편에 있음을 알릴 때 사용합니다." },
  { en: "It's in front of the park.", ko: "공원 앞에 있어요.", tip: "공원 앞쪽 위치를 설명할 때 씁니다." },
  { en: "It's between the cafe and the pharmacy.", ko: "카페와 약국 사이에 있어요.", tip: "두 건물 사이에 위치함을 설명할 때 사용합니다." },
  { en: "You can't miss it.", ko: "쉽게 찾으실 수 있을 거예요.", tip: "눈에 잘 띄는 곳에 있음을 강조할 때 씁니다." },
  { en: "How far is it from here?", ko: "여기서 얼마나 먼가요?", tip: "목적지까지의 거리를 물어볼 때 사용합니다." },
  { en: "Is it within walking distance?", ko: "걸어갈 수 있는 거리인가요?", tip: "도보 이동 가능 여부를 확인할 때 묻습니다." },
  { en: "It takes about ten minutes on foot.", ko: "걸어서 10분 정도 걸려요.", tip: "도보 소요 시간을 안내받을 때 듣는 말입니다." },
  { en: "It's too far to walk.", ko: "걸어가기엔 너무 멀어요.", tip: "도보로 가기 힘든 거리임을 안내받을 때 듣습니다." },
  { en: "You should take a taxi.", ko: "택시를 타는 게 좋겠어요.", tip: "택시 이용을 권유받을 때 듣는 말입니다." },
  { en: "Which bus goes to the city center?", ko: "시내로 가려면 몇 번 버스를 타야 하나요?", tip: "목적지행 버스 번호를 물어볼 때 씁니다." },
  { en: "Where can I catch a taxi?", ko: "택시는 어디서 탈 수 있나요?", tip: "택시 승강장이나 잡기 좋은 곳을 물어볼 때 사용합니다." },
  { en: "I think I'm lost.", ko: "길을 잃은 것 같아요.", tip: "길을 잃었음을 알리고 도움을 청할 때 씁니다." },
  { en: "Could you help me find my way?", ko: "길 찾는 것 좀 도와주시겠어요?", tip: "정중하게 길 안내를 부탁할 때 사용합니다." },
  { en: "What street is this?", ko: "여기가 무슨 거리인가요?", tip: "현재 위치의 거리 이름을 물어볼 때 씁니다." },
  { en: "Where are we now?", ko: "우리 지금 어디에 있나요?", tip: "지도상 현재 위치를 물어볼 때 사용합니다." },
  { en: "Is this the right train for downtown?", ko: "이 기차가 시내로 가는 게 맞나요?", 기: "올바른 기차/전철을 탔는지 확인할 때 묻습니다." },
  { en: "How many stops is it to the airport?", ko: "공항까지 몇 정거장 남았나요?", tip: "남은 정거장 수를 물어볼 때 씁니다." },
  { en: "Please tell me when to get off.", ko: "언제 내려야 하는지 알려주세요.", tip: "내릴 곳을 알려달라고 부탁할 때 사용합니다." },
  { en: "You need to transfer at the next station.", ko: "다음 역에서 환승하셔야 해요.", tip: "환승 안내를 받을 때 듣는 말입니다." },
  { en: "Go down this street.", ko: "이 길을 따라 내려가세요.", tip: "길을 따라 직진하라는 안내입니다." },
  { en: "Go up this street.", ko: "이 길을 따라 올라가세요.", tip: "길을 따라 직진하라는 안내입니다." },
  { en: "Walk past the supermarket.", ko: "슈퍼마켓을 지나서 걸어가세요.", tip: "특정 건물을 지나치라는 안내입니다." },
  { en: "It's at the end of the road.", ko: "길 끝에 있어요.", tip: "막다른 곳이나 길 끝에 위치함을 알릴 때 씁니다." },
  { en: "It's on the corner of Main Street and First Avenue.", ko: "메인 스트리트와 1번가 모퉁이에 있어요.", tip: "두 거리가 만나는 모퉁이 위치를 설명할 때 사용합니다." },
  { en: "Keep going until you see a gas station.", ko: "주유소가 보일 때까지 계속 가세요.", tip: "특정 랜드마크가 나올 때까지 직진하라는 안내입니다." },
  { en: "Cross the bridge.", ko: "다리를 건너세요.", tip: "다리를 건너가라는 안내입니다." },
  { en: "Go through the tunnel.", ko: "터널을 통과하세요.", tip: "터널을 지나가라는 안내입니다." },
  { en: "Take the first right.", ko: "첫 번째 골목에서 오른쪽으로 가세요.", tip: "첫 번째 교차로에서 우회전하라는 안내입니다." },
  { en: "Take the second left.", ko: "두 번째 골목에서 왼쪽으로 가세요.", tip: "두 번째 교차로에서 좌회전하라는 안내입니다." },
  { en: "It's just around the corner.", ko: "바로 모퉁이 돌아서 있어요.", tip: "모퉁이만 돌면 바로 있음을 알릴 때 씁니다." },
  { en: "It's opposite the hospital.", ko: "병원 맞은편에 있어요.", tip: "맞은편 위치를 설명할 때 사용합니다." },
  { en: "Where is the nearest restroom?", ko: "가장 가까운 화장실이 어디인가요?", tip: "화장실을 급히 찾을 때 묻습니다." },
  { en: "Where is the tourist information center?", ko: "관광 안내소가 어디인가요?", tip: "관광 정보를 얻기 위해 안내소를 찾을 때 씁니다." },
  { en: "Is there a convenience store around here?", ko: "이 근처에 편의점이 있나요?", tip: "가까운 편의점을 찾을 때 묻습니다." },
  { en: "Can you point me in the right direction?", ko: "맞는 방향을 가리켜 주시겠어요?", tip: "가야 할 방향을 손가락으로 가리켜 달라고 할 때 씁니다." },
  { en: "I'm trying to find the central station.", ko: "중앙역을 찾고 있어요.", tip: "목적지를 밝히며 길을 물어볼 때 사용합니다." },
  { en: "Do you know where the library is?", ko: "도서관이 어디 있는지 아시나요?", tip: "특정 건물의 위치를 물어볼 때 씁니다." },
  { en: "Am I on the right road for the beach?", ko: "해변으로 가는 길이 맞나요?", tip: "올바른 길로 가고 있는지 확인할 때 묻습니다." },
  { en: "You're going the wrong way.", ko: "반대 방향으로 가고 계세요.", tip: "길을 잘못 들었음을 안내받을 때 듣는 말입니다." },
  { en: "Turn around and go back.", ko: "돌아서 다시 가세요.", tip: "왔던 길로 되돌아가라는 안내입니다." },
  { en: "It's about a mile down the road.", ko: "길을 따라 1마일 정도 가면 있어요.", tip: "거리와 방향을 함께 안내받을 때 듣습니다." },
  { en: "Follow the signs for the airport.", ko: "공항 표지판을 따라가세요.", tip: "표지판 안내를 따르라는 말을 들을 때 씁니다." },
  { en: "Where is the ticket office?", ko: "매표소가 어디인가요?", tip: "표를 사는 곳을 찾을 때 묻습니다." },
  { en: "Where is platform number five?", ko: "5번 플랫폼이 어디인가요?", tip: "기차나 전철 타는 플랫폼을 찾을 때 씁니다." },
  { en: "Which exit should I take?", ko: "어느 출구로 나가야 하나요?", tip: "지하철역 등에서 나갈 출구를 물어볼 때 사용합니다." },
  { en: "Take exit number three.", ko: "3번 출구로 나가세요.", tip: "출구 번호를 안내받을 때 듣는 말입니다." },
  { en: "Go up the stairs.", ko: "계단으로 올라가세요.", tip: "계단 이용을 안내받을 때 듣습니다." },
  { en: "Go down the escalator.", ko: "에스컬레이터를 타고 내려가세요.", tip: "에스컬레이터 이용을 안내받을 때 듣습니다." },
  { en: "Take the elevator to the second floor.", ko: "엘리베이터를 타고 2층으로 가세요.", tip: "엘리베이터 이용 및 층수를 안내받을 때 듣습니다." },
  { en: "Where is the taxi stand?", ko: "택시 승강장이 어디인가요?", tip: "택시 타는 곳을 찾을 때 묻습니다." },
  { en: "Is this the line for the bus?", ko: "이게 버스 타는 줄인가요?", tip: "줄을 서기 전 올바른 줄인지 확인할 때 씁니다." },
  { en: "Does this bus stop at the museum?", ko: "이 버스는 박물관에 정차하나요?", tip: "버스의 목적지를 확인할 때 묻습니다." },
  { en: "How often do the buses run?", ko: "버스는 얼마나 자주 다니나요?", tip: "배차 간격을 물어볼 때 사용합니다." },
  { en: "The next bus is in fifteen minutes.", ko: "다음 버스는 15분 후에 옵니다.", tip: "다음 버스 도착 시간을 안내받을 때 듣습니다." },
  { en: "Where can I buy a ticket?", ko: "표는 어디서 살 수 있나요?", tip: "매표소나 발권기 위치를 물어볼 때 씁니다." },
  { en: "Can I buy a ticket on the bus?", ko: "버스 안에서 표를 살 수 있나요?", tip: "차내 발권 가능 여부를 확인할 때 묻습니다." },
  { en: "How much is the fare?", ko: "요금이 얼마인가요?", tip: "교통 요금을 물어볼 때 사용합니다." },
  { en: "Do I need exact change?", ko: "잔돈을 정확히 맞춰 내야 하나요?", tip: "거스름돈을 주는지 확인할 때 묻습니다." },
  { en: "Please let me off here.", ko: "여기서 내려주세요.", tip: "택시나 버스에서 하차를 요청할 때 씁니다." },
  { en: "Could you drop me off at the corner?", ko: "모퉁이에서 내려주시겠어요?", tip: "특정 지점에서 하차를 요청할 때 사용합니다." },
  { en: "I need to go to this hotel.", ko: "이 호텔로 가야 합니다.", tip: "택시 기사에게 목적지를 알릴 때 씁니다." },
  { en: "Can you take me to this address?", ko: "이 주소로 데려다 주시겠어요?", tip: "주소를 보여주며 택시 기사에게 요청할 때 사용합니다." },
  { en: "Please use the meter.", ko: "미터기를 켜주세요.", tip: "택시 미터기 사용을 요구할 때 씁니다." },
  { en: "How long will the ride take?", ko: "차로 얼마나 걸릴까요?", tip: "이동 소요 시간을 물어볼 때 사용합니다." },
  { en: "Is there a lot of traffic?", ko: "차가 많이 막히나요?", tip: "교통 체증 여부를 물어볼 때 씁니다." },
  { en: "Please take the fastest route.", ko: "가장 빠른 길로 가주세요.", tip: "빠른 길로 가달라고 요청할 때 사용합니다." },
  { en: "Could you drive a little slower?", ko: "조금만 천천히 운전해 주시겠어요?", tip: "과속하는 기사에게 속도를 줄여달라고 요청할 때 씁니다." },
  { en: "Stop here, please.", ko: "여기 세워주세요.", tip: "목적지에 도착하여 정차를 요청할 때 사용합니다." },
  { en: "Keep the change.", ko: "잔돈은 가지세요.", tip: "거스름돈을 팁으로 줄 때 씁니다." },
  { en: "Can I get a receipt?", ko: "영수증 받을 수 있을까요?", tip: "결제 후 영수증을 요구할 때 사용합니다." },
  { en: "Where can I rent a car?", ko: "렌터카는 어디서 빌릴 수 있나요?", tip: "렌터카 업체를 찾을 때 묻습니다." },
  { en: "Where is the nearest gas station?", ko: "가장 가까운 주유소가 어디인가요?", tip: "주유소를 찾을 때 사용합니다." },
  { en: "Fill it up, please.", ko: "가득 채워주세요.", tip: "주유소에서 연료를 가득 채워달라고 할 때 씁니다." },
  { en: "Where can I park my car?", ko: "차는 어디에 주차할 수 있나요?", tip: "주차장 위치를 물어볼 때 사용합니다." },
  { en: "Is this a paid parking lot?", ko: "유료 주차장인가요?", tip: "주차 요금 부과 여부를 확인할 때 묻습니다." },
  { en: "How much is parking per hour?", ko: "시간당 주차 요금이 얼마인가요?", tip: "주차 요금을 물어볼 때 씁니다." },
  { en: "You can't park here.", ko: "여기에 주차하시면 안 됩니다.", tip: "주차 금지 구역임을 안내받을 때 듣습니다." },
  { en: "My car was towed.", ko: "제 차가 견인되었어요.", tip: "차량이 견인되었음을 알릴 때 사용합니다." },
  { en: "Where is the car rental return?", ko: "렌터카 반납 장소가 어디인가요?", tip: "렌터카를 반납할 곳을 찾을 때 묻습니다." },
  { en: "I need a map of the city.", ko: "시내 지도가 필요해요.", tip: "관광 안내소 등에서 지도를 요청할 때 씁니다." },
  { en: "Do you have a subway map?", ko: "지하철 노선도가 있나요?", tip: "지하철 노선도를 요청할 때 사용합니다." },
  { en: "Can I walk there safely at night?", ko: "밤에 거기로 걸어가도 안전한가요?", tip: "야간 치안 상태를 물어볼 때 씁니다." },
  { en: "Is this a safe neighborhood?", ko: "여기는 안전한 동네인가요?", tip: "해당 지역의 치안을 물어볼 때 사용합니다." },
  { en: "I'm looking for a good restaurant around here.", ko: "이 근처에 좋은 식당을 찾고 있어요.", tip: "주변 식당 추천을 부탁할 때 씁니다." },
  { en: "Where is the main shopping street?", ko: "메인 쇼핑 거리가 어디인가요?", tip: "번화가나 쇼핑 거리를 찾을 때 묻습니다." },
  { en: "Thank you for your directions.", ko: "길을 알려주셔서 감사합니다.", tip: "길 안내를 받은 후 감사 인사를 할 때 씁니다." },
  { en: "You've been very helpful.", ko: "정말 큰 도움이 되었습니다.", tip: "도움을 준 사람에게 고마움을 표할 때 사용합니다." }
];

const missingWords = {
  "nearest": { en: "nearest", ko: "가장 가까운", type: "adjective" },
  "subway": { en: "subway", ko: "지하철", type: "noun" },
  "station": { en: "station", ko: "역, 정거장", type: "noun" },
  "museum": { en: "museum", ko: "박물관", type: "noun" },
  "bus": { en: "bus", ko: "버스", type: "noun" },
  "stop": { en: "stop", ko: "정류장, 멈추다", type: "noun" },
  "map": { en: "map", ko: "지도", type: "noun" },
  "headed": { en: "headed", ko: "향하는", type: "adjective" },
  "straight": { en: "straight", ko: "직진하여, 똑바로", type: "adverb" },
  "blocks": { en: "blocks", ko: "블록들", type: "noun" },
  "turn": { en: "turn", ko: "돌다", type: "verb" },
  "left": { en: "left", ko: "왼쪽", type: "noun" },
  "right": { en: "right", ko: "오른쪽, 맞는", type: "noun" },
  "intersection": { en: "intersection", ko: "교차로", type: "noun" },
  "traffic": { en: "traffic", ko: "교통", type: "noun" },
  "light": { en: "light", ko: "신호등, 빛", type: "noun" },
  "across": { en: "across", ko: "건너편에, 가로질러", type: "preposition" },
  "street": { en: "street", ko: "거리, 길", type: "noun" },
  "bank": { en: "bank", ko: "은행", type: "noun" },
  "post": { en: "post", ko: "우편", type: "noun" },
  "office": { en: "office", ko: "사무실, 우체국", type: "noun" },
  "behind": { en: "behind", ko: "뒤에", type: "preposition" },
  "tall": { en: "tall", ko: "키가 큰, 높은", type: "adjective" },
  "building": { en: "building", ko: "건물", type: "noun" },
  "front": { en: "front", ko: "앞", type: "noun" },
  "park": { en: "park", ko: "공원, 주차하다", type: "noun" },
  "between": { en: "between", ko: "사이에", type: "preposition" },
  "pharmacy": { en: "pharmacy", ko: "약국", type: "noun" },
  "miss": { en: "miss", ko: "놓치다", type: "verb" },
  "far": { en: "far", ko: "먼", type: "adjective" },
  "within": { en: "within", ko: "이내에", type: "preposition" },
  "walking": { en: "walking", ko: "걷는, 도보", type: "noun" },
  "distance": { en: "distance", ko: "거리", type: "noun" },
  "takes": { en: "takes", ko: "걸리다 (시간이)", type: "verb" },
  "ten": { en: "ten", ko: "10", type: "number" },
  "foot": { en: "foot", ko: "발, 도보", type: "noun" },
  "taxi": { en: "taxi", ko: "택시", type: "noun" },
  "center": { en: "center", ko: "중심, 센터", type: "noun" },
  "catch": { en: "catch", ko: "잡다, 타다", type: "verb" },
  "lost": { en: "lost", ko: "길을 잃은", type: "adjective" },
  "road": { en: "road", ko: "길, 도로", type: "noun" },
  "corner": { en: "corner", ko: "모퉁이", type: "noun" },
  "main": { en: "main", ko: "주요한, 메인", type: "adjective" },
  "first": { en: "first", ko: "첫 번째", type: "adjective" },
  "avenue": { en: "avenue", ko: "거리, 가", type: "noun" },
  "gas": { en: "gas", ko: "가스, 주유", type: "noun" },
  "bridge": { en: "bridge", ko: "다리", type: "noun" },
  "tunnel": { en: "tunnel", ko: "터널", type: "noun" },
  "opposite": { en: "opposite", ko: "맞은편의", type: "preposition" },
  "restroom": { en: "restroom", ko: "화장실", type: "noun" },
  "tourist": { en: "tourist", ko: "관광객", type: "noun" },
  "information": { en: "information", ko: "정보, 안내", type: "noun" },
  "convenience": { en: "convenience", ko: "편의", type: "noun" },
  "store": { en: "store", ko: "가게, 상점", type: "noun" },
  "point": { en: "point", ko: "가리키다", type: "verb" },
  "direction": { en: "direction", ko: "방향", type: "noun" },
  "central": { en: "central", ko: "중앙의", type: "adjective" },
  "library": { en: "library", ko: "도서관", type: "noun" },
  "beach": { en: "beach", ko: "해변", type: "noun" },
  "wrong": { en: "wrong", ko: "잘못된", type: "adjective" },
  "around": { en: "around", ko: "주위에, 돌아서", type: "preposition" },
  "mile": { en: "mile", ko: "마일 (거리 단위)", type: "noun" },
  "signs": { en: "signs", ko: "표지판들", type: "noun" },
  "ticket": { en: "ticket", ko: "표, 티켓", type: "noun" },
  "platform": { en: "platform", ko: "플랫폼, 승강장", type: "noun" },
  "five": { en: "five", ko: "5", type: "number" },
  "exit": { en: "exit", ko: "출구", type: "noun" },
  "three": { en: "three", ko: "3", type: "number" },
  "stairs": { en: "stairs", ko: "계단", type: "noun" },
  "escalator": { en: "escalator", ko: "에스컬레이터", type: "noun" },
  "elevator": { en: "elevator", ko: "엘리베이터", type: "noun" },
  "second": { en: "second", ko: "두 번째, 2초", type: "adjective" },
  "floor": { en: "floor", ko: "층, 바닥", type: "noun" },
  "stand": { en: "stand", ko: "승강장, 서다", type: "noun" },
  "line": { en: "line", ko: "줄, 선", type: "noun" },
  "run": { en: "run", ko: "운행하다, 달리다", type: "verb" },
  "fifteen": { en: "fifteen", ko: "15", type: "number" },
  "buy": { en: "buy", ko: "사다", type: "verb" },
  "fare": { en: "fare", ko: "요금", type: "noun" },
  "exact": { en: "exact", ko: "정확한", type: "adjective" },
  "change": { en: "change", ko: "잔돈, 거스름돈", type: "noun" },
  "drop": { en: "drop", ko: "내려주다, 떨어뜨리다", type: "verb" },
  "ride": { en: "ride", ko: "타기, 승차", type: "noun" },
  "lot": { en: "lot", ko: "많음, 주차장", type: "noun" },
  "fastest": { en: "fastest", ko: "가장 빠른", type: "adjective" },
  "route": { en: "route", ko: "경로, 길", type: "noun" },
  "drive": { en: "drive", ko: "운전하다", type: "verb" },
  "slower": { en: "slower", ko: "더 느리게", type: "adverb" },
  "rent": { en: "rent", ko: "빌리다, 대여하다", type: "verb" },
  "fill": { en: "fill", ko: "채우다", type: "verb" },
  "paid": { en: "paid", ko: "유료의, 지불된", type: "adjective" },
  "parking": { en: "parking", ko: "주차", type: "noun" },
  "per": { en: "per", ko: "~당, 마다", type: "preposition" },
  "hour": { en: "hour", ko: "시간", type: "noun" },
  "towed": { en: "towed", ko: "견인된", type: "adjective" },
  "return": { en: "return", ko: "반납, 돌아오다", type: "noun" },
  "safely": { en: "safely", ko: "안전하게", type: "adverb" },
  "neighborhood": { en: "neighborhood", ko: "동네, 이웃", type: "noun" },
  "helpful": { en: "helpful", ko: "도움이 되는", type: "adjective" },
  "i'd": { en: "I'd", ko: "나는 ~할 것이다 (I would/had)", type: "pronoun" },
  "hasn't": { en: "hasn't", ko: "~하지 않았다 (has not)", type: "verb" },
  "kim": { en: "Kim", ko: "킴 (이름)", type: "noun" },
  "isn't": { en: "isn't", ko: "~이 아니다 (is not)", type: "verb" },
  "wake-up": { en: "wake-up", ko: "기상, 모닝콜", type: "noun" },
  "conditioner": { en: "conditioner", ko: "린스, 컨디셔너", type: "noun" },
  "didn't": { en: "didn't", ko: "~하지 않았다 (did not)", type: "verb" },
  "pm": { en: "PM", ko: "오후", type: "noun" },
  "dish": { en: "dish", ko: "요리, 접시", type: "noun" },
  "nut": { en: "nut", ko: "견과류", type: "noun" },
  "plates": { en: "plates", ko: "접시들", type: "noun" },
  "four": { en: "four", ko: "4", type: "number" },
  "minutes": { en: "minutes", ko: "분", type: "noun" },
  "i'll": { en: "I'll", ko: "나는 ~할 것이다 (I will)", type: "pronoun" },
  "done": { en: "done", ko: "완료된", type: "adjective" },
  "less": { en: "less", ko: "더 적은", type: "adjective" },
  "contain": { en: "contain", ko: "포함하다", type: "verb" },
  "i'm": { en: "I'm", ko: "나는 ~이다 (I am)", type: "pronoun" },
  "glass": { en: "glass", ko: "유리잔", type: "noun" },
  "red": { en: "red", ko: "빨간색", type: "noun" },
  "we'd": { en: "we'd", ko: "우리는 ~할 것이다 (we would/had)", type: "pronoun" },
  "to-go": { en: "to-go", ko: "포장용의", type: "adjective" },
  "espresso": { en: "espresso", ko: "에스프레소", type: "noun" },
  "what's": { en: "what's", ko: "무엇이 ~인가 (what is)", type: "pronoun" },
  "tables": { en: "tables", ko: "테이블들", type: "noun" },
  "gluten-free": { en: "gluten-free", ko: "글루텐 프리의", type: "adjective" },
  "pizza": { en: "pizza", ko: "피자", type: "noun" },
  "eggs": { en: "eggs", ko: "계란들", type: "noun" },
  "sunny-side": { en: "sunny-side", ko: "한쪽만 익힌 (계란 프라이)", type: "adjective" },
  "baby": { en: "baby", ko: "아기", type: "noun" },
  "serve": { en: "serve", ko: "제공하다, 서빙하다", type: "verb" },
  "tokyo": { en: "Tokyo", ko: "도쿄", type: "noun" },
  "address": { en: "address", ko: "주소", type: "noun" },
  "drivers": { en: "drivers", ko: "운전자들", type: "noun" },
  "different": { en: "different", ko: "다른", type: "adjective" },
  "color": { en: "color", ko: "색깔", type: "noun" },
  "fitting": { en: "fitting", ko: "피팅, 입어보는", type: "adjective" },
  "sale": { en: "sale", ko: "할인, 판매", type: "noun" },
  "men's": { en: "men's", ko: "남성용의", type: "adjective" },
  "women's": { en: "women's", ko: "여성용의", type: "adjective" },
  "children's": { en: "children's", ko: "아동용의", type: "adjective" },
  "muffin": { en: "muffin", ko: "머핀", type: "noun" },
  "straws": { en: "straws", ko: "빨대들", type: "noun" },
  "stirrer": { en: "stirrer", ko: "젓개, 스틱", type: "noun" },
  "near": { en: "near", ko: "가까운, 근처에", type: "preposition" },
  "cafe": { en: "cafe", ko: "카페", type: "noun" },
  "i've": { en: "I've", ko: "나는 ~했다 (I have)", type: "pronoun" },
  "can't": { en: "can't", ko: "~할 수 없다 (cannot)", type: "verb" },
  "leg": { en: "leg", ko: "다리", type: "noun" },
  "breathe": { en: "breathe", ko: "숨쉬다", type: "verb" }
};

const sentencesFile = 'src/sentences.json';
const dictionaryFile = 'src/dictionary.json';

const sentencesData = JSON.parse(fs.readFileSync(sentencesFile, 'utf8'));
const dictionaryData = JSON.parse(fs.readFileSync(dictionaryFile, 'utf8'));

if (!sentencesData.navigation) {
  sentencesData.navigation = [];
}

let addedSentences = 0;
for (const sentence of newSentences) {
  const exists = sentencesData.navigation.some(s => s.en === sentence.en);
  if (!exists) {
    sentencesData.navigation.push(sentence);
    addedSentences++;
  }
}

let addedWords = 0;
for (const [word, def] of Object.entries(missingWords)) {
  const lowerWord = word.toLowerCase();
  if (!dictionaryData[lowerWord]) {
    dictionaryData[lowerWord] = def;
    addedWords++;
  }
}

fs.writeFileSync(sentencesFile, JSON.stringify(sentencesData, null, 2));
fs.writeFileSync(dictionaryFile, JSON.stringify(dictionaryData, null, 2));

console.log(`Added ${addedSentences} sentences to navigation category.`);
console.log(`Added ${addedWords} missing words to dictionary.`);
