const fs = require('fs');

const missingWords = {
  "tourists": { en: "tourists", ko: "관광객들", type: "noun" },
  "data-only": { en: "data-only", ko: "데이터 전용", type: "adjective" },
  "network": { en: "network", ko: "네트워크, 통신망", type: "noun" },
  "coverage": { en: "coverage", ko: "수신 범위, 보급 범위", type: "noun" },
  "compatible": { en: "compatible", ko: "호환되는", type: "adjective" },
  "nano": { en: "nano", ko: "나노 (크기 단위)", type: "noun" },
  "cut": { en: "cut", ko: "자르다", type: "verb" },
  "fit": { en: "fit", ko: "맞다, 적합하다", type: "verb" },
  "calls": { en: "calls", ko: "통화, 전화", type: "noun" },
  "talk": { en: "talk", ko: "말하다, 통화", type: "verb" },
  "text": { en: "text", ko: "문자, 텍스트", type: "noun" },
  "messages": { en: "messages", ko: "메시지들", type: "noun" },
  "validity": { en: "validity", ko: "유효함, 타당성", type: "noun" },
  "period": { en: "period", ko: "기간, 시기", type: "noun" },
  "voucher": { en: "voucher", ko: "바우처, 상품권", type: "noun" },
  "happens": { en: "happens", ko: "일어나다, 발생하다", type: "verb" },
  "high-speed": { en: "high-speed", ko: "고속의", type: "adjective" },
  "throttled": { en: "throttled", ko: "제한된, 조절된", type: "adjective" },
  "gigabytes": { en: "gigabytes", ko: "기가바이트", type: "noun" },
  "iphone": { en: "iPhone", ko: "아이폰", type: "noun" },
  "qr": { en: "QR", ko: "큐알", type: "noun" },
  "accidentally": { en: "accidentally", ko: "실수로, 우연히", type: "adverb" },
  "deleted": { en: "deleted", ko: "삭제된", type: "adjective" },
  "profile": { en: "profile", ko: "프로필", type: "noun" },
  "restart": { en: "restart", ko: "재시작하다", type: "verb" },
  "activation": { en: "activation", ko: "활성화, 개통", type: "noun" },
  "says": { en: "says", ko: "말하다, 쓰여 있다", type: "verb" },
  "screen": { en: "screen", ko: "화면, 스크린", type: "noun" },
  "3g": { en: "3G", ko: "3세대 이동통신", type: "noun" },
  "4g": { en: "4G", ko: "4세대 이동통신", type: "noun" },
  "why": { en: "why", ko: "왜", type: "adverb" },
  "outage": { en: "outage", ko: "정전, 단전, 통신 장애", type: "noun" },
  "'invalid": { en: "invalid", ko: "유효하지 않은", type: "adjective" },
  "sim'": { en: "SIM", ko: "유심", type: "noun" },
  "replacement": { en: "replacement", ko: "교체, 대체", type: "noun" },
  "registration": { en: "registration", ko: "등록", type: "noun" },
  "activated": { en: "activated", ko: "활성화된, 개통된", type: "adjective" },
  "status": { en: "status", ko: "상태", type: "noun" },
  "apn": { en: "APN", ko: "액세스 포인트 이름", type: "noun" },
  "settings": { en: "settings", ko: "설정", type: "noun" },
  "manually": { en: "manually", ko: "수동으로", type: "adverb" },
  "type": { en: "type", ko: "입력하다, 치다", type: "verb" },
  "cannot": { en: "cannot", ko: "할 수 없다", type: "verb" },
  "receiving": { en: "receiving", ko: "받는 중인", type: "verb" },
  "roaming": { en: "roaming", ko: "로밍", type: "noun" },
  "portable": { en: "portable", ko: "휴대용의", type: "adjective" },
  "router": { en: "router", ko: "라우터, 공유기", type: "noun" },
  "devices": { en: "devices", ko: "기기들, 장치들", type: "noun" },
  "turning": { en: "turning", ko: "돌리는, 켜는", type: "verb" },
  "keeps": { en: "keeps", ko: "계속하다", type: "verb" },
  "disconnecting": { en: "disconnecting", ko: "연결이 끊어지는", type: "verb" },
  "hotspot": { en: "hotspot", ko: "핫스팟", type: "noun" },
  "select": { en: "select", ko: "선택하다", type: "verb" },
  "unlock": { en: "unlock", ko: "잠금을 풀다", type: "verb" },
  "united": { en: "united", ko: "연합된, 통합된", type: "adjective" },
  "states": { en: "states", ko: "주들, 국가들", type: "noun" },
  "message": { en: "message", ko: "메시지", type: "noun" },
  "whatsapp": { en: "WhatsApp", ko: "왓츠앱", type: "noun" },
  "social": { en: "social", ko: "소셜, 사회적인", type: "adjective" },
  "media": { en: "media", ko: "미디어, 매체", type: "noun" },
  "allowance": { en: "allowance", ko: "허용량, 수당", type: "noun" },
  "tethering": { en: "tethering", ko: "테더링", type: "noun" },
  "via": { en: "via", ko: "~을 통하여", type: "preposition" },
  "personal": { en: "personal", ko: "개인적인", type: "adjective" },
  "insert": { en: "insert", ko: "삽입하다, 넣다", type: "verb" },
  "paperclip": { en: "paperclip", ko: "종이 클립", type: "noun" },
  "dying": { en: "dying", ko: "죽어가는, 닳아가는", type: "adjective" },
  "minute": { en: "minute", ko: "분, 잠깐", type: "noun" },
  "mobile": { en: "mobile", ko: "모바일, 휴대용의", type: "adjective" },
  "universal": { en: "universal", ko: "보편적인, 만능의", type: "adjective" },
  "english-speaking": { en: "English-speaking", ko: "영어를 하는", type: "adjective" },
  "operator": { en: "operator", ko: "교환원, 운영자", type: "noun" },
  "spam": { en: "spam", ko: "스팸", type: "noun" },
  "voicemail": { en: "voicemail", ko: "음성 사서함", type: "noun" },
  "disable": { en: "disable", ko: "비활성화하다", type: "verb" },
  "subscription": { en: "subscription", ko: "구독, 가입", type: "noun" },
  "unused": { en: "unused", ko: "사용되지 않은", type: "adjective" },
  "advertised": { en: "advertised", ko: "광고된", type: "adjective" },
  "load": { en: "load", ko: "불러오다, 로드하다", type: "verb" },
  "web": { en: "web", ko: "웹", type: "noun" },
  "pages": { en: "pages", ko: "페이지들", type: "noun" },
  "maps": { en: "maps", ko: "지도들", type: "noun" },
  "loading": { en: "loading", ko: "로딩 중인", type: "verb" },
  "connection": { en: "connection", ko: "연결", type: "noun" },
  "weeks": { en: "weeks", ko: "주들", type: "noun" },
  "entered": { en: "entered", ko: "입력된, 들어간", type: "verb" },
  "puk": { en: "PUK", ko: "퍼스널 언락 키", type: "noun" },
  "scratch": { en: "scratch", ko: "긁다", type: "verb" },
  "reveal": { en: "reveal", ko: "드러내다, 밝히다", type: "verb" },
  "expires": { en: "expires", ko: "만료되다", type: "verb" },
  "setting": { en: "setting", ko: "설정", type: "noun" }
};

const dictionaryFile = 'src/dictionary.json';
const dictionaryData = JSON.parse(fs.readFileSync(dictionaryFile, 'utf8'));

let addedWords = 0;
for (const [word, def] of Object.entries(missingWords)) {
  const lowerWord = word.toLowerCase().replace(/[^a-z0-9-']/g, '');
  if (!dictionaryData[lowerWord]) {
    dictionaryData[lowerWord] = def;
    addedWords++;
  }
}

fs.writeFileSync(dictionaryFile, JSON.stringify(dictionaryData, null, 2));
console.log(`Added ${addedWords} missing words to dictionary.`);
