const fs = require('fs');

const sentences = [
  { en: "Can I get a large cappuccino?", ko: "카푸치노 라지 사이즈로 주시겠어요?", tip: "사이즈와 음료를 함께 말합니다." },
  { en: "I'll have a medium latte.", ko: "미디엄 라떼로 할게요.", tip: "I'll have ~ 패턴을 사용해 주문합니다." },
  { en: "Do you have soy milk?", ko: "두유 있나요?", tip: "우유 대체 옵션을 물어볼 때 사용합니다." },
  { en: "Can you make it decaf?", ko: "디카페인으로 만들어 주실 수 있나요?", tip: "디카페인 옵션을 요청할 때 사용합니다." },
  { en: "I'd like a slice of carrot cake.", ko: "당근 케이크 한 조각 주세요.", tip: "디저트를 주문할 때 사용합니다." },
  { en: "Could I get that warmed up?", ko: "그거 데워 주실 수 있나요?", tip: "빵이나 페이스트리를 데워달라고 할 때 사용합니다." },
  { en: "Is there a restroom for customers?", ko: "고객용 화장실이 있나요?", tip: "화장실 위치를 물어볼 때 사용합니다." },
  { en: "What's the Wi-Fi password?", ko: "와이파이 비밀번호가 뭐예요?", tip: "와이파이 비밀번호를 물어볼 때 사용합니다." },
  { en: "Can I get the receipt, please?", ko: "영수증 좀 주시겠어요?", tip: "영수증을 요청할 때 사용합니다." },
  { en: "Do you accept Apple Pay?", ko: "애플페이 되나요?", tip: "결제 수단을 물어볼 때 사용합니다." },
  { en: "I'll pay with cash.", ko: "현금으로 계산할게요.", tip: "현금 결제를 원할 때 사용합니다." },
  { en: "Can I get a carrier for these?", ko: "이것들 담아갈 캐리어 주시겠어요?", tip: "음료 여러 잔을 담을 캐리어를 요청할 때 사용합니다." },
  { en: "Could I have an extra cup?", ko: "빈 컵 하나 더 주실 수 있나요?", tip: "여분의 컵을 요청할 때 사용합니다." },
  { en: "Is this table taken?", ko: "이 자리 비어 있나요?", tip: "자리가 비어 있는지 물어볼 때 사용합니다." },
  { en: "Can we sit anywhere?", ko: "아무데나 앉아도 되나요?", tip: "자리를 자유롭게 선택해도 되는지 물어볼 때 사용합니다." },
  { en: "What time do you close?", ko: "몇 시에 문 닫나요?", tip: "영업 종료 시간을 물어볼 때 사용합니다." },
  { en: "Do you have any vegan options?", ko: "비건 메뉴 있나요?", tip: "비건 메뉴를 찾을 때 사용합니다." },
  { en: "I'd like a black coffee.", ko: "블랙 커피 주세요.", tip: "아메리카노나 드립 커피를 주문할 때 사용합니다." },
  { en: "Can I get a caramel macchiato?", ko: "카라멜 마끼아또 주시겠어요?", tip: "특정 음료를 주문할 때 사용합니다." },
  { en: "With whipped cream on top, please.", ko: "위에 휘핑크림 올려 주세요.", tip: "휘핑크림 추가를 요청할 때 사용합니다." },
  { en: "No whipped cream, please.", ko: "휘핑크림은 빼 주세요.", tip: "휘핑크림을 빼달라고 할 때 사용합니다." },
  { en: "Can I get a pump of vanilla syrup?", ko: "바닐라 시럽 한 펌프 넣어 주시겠어요?", tip: "시럽 추가를 요청할 때 사용합니다." },
  { en: "I'd like it less sweet.", ko: "덜 달게 해 주세요.", tip: "단맛을 조절하고 싶을 때 사용합니다." },
  { en: "Can I get extra ice?", ko: "얼음 많이 넣어 주세요.", tip: "얼음을 많이 원할 때 사용합니다." },
  { en: "Light ice, please.", ko: "얼음은 조금만 넣어 주세요.", tip: "얼음을 적게 원할 때 사용합니다." },
  { en: "Can I get a hot tea?", ko: "따뜻한 차 주시겠어요?", tip: "따뜻한 차를 주문할 때 사용합니다." },
  { en: "What kind of tea do you have?", ko: "어떤 종류의 차가 있나요?", tip: "차 종류를 물어볼 때 사용합니다." },
  { en: "I'll have an iced green tea.", ko: "아이스 녹차로 할게요.", tip: "아이스 티를 주문할 때 사용합니다." },
  { en: "Can I get a smoothie?", ko: "스무디 주시겠어요?", tip: "스무디를 주문할 때 사용합니다." },
  { en: "What flavors do you have?", ko: "어떤 맛이 있나요?", tip: "맛 종류를 물어볼 때 사용합니다." },
  { en: "I'd like a strawberry smoothie.", ko: "딸기 스무디 주세요.", tip: "특정 맛의 스무디를 주문할 때 사용합니다." },
  { en: "Can I get a bagel with cream cheese?", ko: "크림치즈 바글 주시겠어요?", tip: "베이글을 주문할 때 사용합니다." },
  { en: "Could you toast the bagel?", ko: "베이글 구워 주실 수 있나요?", tip: "베이글을 구워달라고 할 때 사용합니다." },
  { en: "I'll have a croissant.", ko: "크루아상으로 할게요.", tip: "크루아상을 주문할 때 사용합니다." },
  { en: "Do you have any muffins?", ko: "머핀 있나요?", tip: "머핀이 있는지 물어볼 때 사용합니다." },
  { en: "I'd like a blueberry muffin.", ko: "블루베리 머핀 주세요.", tip: "특정 맛의 머핀을 주문할 때 사용합니다." },
  { en: "Can I get a sandwich?", ko: "샌드위치 주시겠어요?", tip: "샌드위치를 주문할 때 사용합니다." },
  { en: "What kind of sandwiches do you have?", ko: "어떤 종류의 샌드위치가 있나요?", tip: "샌드위치 종류를 물어볼 때 사용합니다." },
  { en: "I'll have a turkey sandwich.", ko: "칠면조 샌드위치로 할게요.", tip: "특정 샌드위치를 주문할 때 사용합니다." },
  { en: "Can I get a salad?", ko: "샐러드 주시겠어요?", tip: "샐러드를 주문할 때 사용합니다." },
  { en: "What kind of dressing comes with it?", ko: "어떤 드레싱이 같이 나오나요?", tip: "드레싱 종류를 물어볼 때 사용합니다." },
  { en: "I'd like the dressing on the side.", ko: "드레싱은 따로 주세요.", tip: "드레싱을 따로 달라고 할 때 사용합니다." },
  { en: "Can I get a bottle of water?", ko: "생수 한 병 주시겠어요?", tip: "생수를 주문할 때 사용합니다." },
  { en: "Do you have sparkling water?", ko: "탄산수 있나요?", tip: "탄산수가 있는지 물어볼 때 사용합니다." },
  { en: "I'll have a sparkling water.", ko: "탄산수 하나 주세요.", tip: "탄산수를 주문할 때 사용합니다." },
  { en: "Can I get a cup of tap water?", ko: "수돗물 한 잔 주시겠어요?", tip: "수돗물을 요청할 때 사용합니다." },
  { en: "Is there a charge for tap water?", ko: "수돗물은 유료인가요?", tip: "수돗물 요금을 물어볼 때 사용합니다." },
  { en: "Can I get some napkins, please?", ko: "냅킨 좀 주시겠어요?", tip: "냅킨을 요청할 때 사용합니다." },
  { en: "Could I have a straw?", ko: "빨대 하나 주실 수 있나요?", tip: "빨대를 요청할 때 사용합니다." },
  { en: "Do you have paper straws?", ko: "종이 빨대 있나요?", tip: "종이 빨대를 찾을 때 사용합니다." },
  { en: "Can I get a stirrer?", ko: "젓는 막대 주시겠어요?", tip: "젓는 막대를 요청할 때 사용합니다." },
  { en: "Where can I find sugar?", ko: "설탕은 어디 있나요?", tip: "설탕 위치를 물어볼 때 사용합니다." },
  { en: "Do you have artificial sweeteners?", ko: "인공 감미료 있나요?", tip: "인공 감미료를 찾을 때 사용합니다." },
  { en: "Can I get some milk for my coffee?", ko: "커피에 넣을 우유 좀 주시겠어요?", tip: "우유를 요청할 때 사용합니다." },
  { en: "Is there a trash can around here?", ko: "이 근처에 쓰레기통이 있나요?", tip: "쓰레기통 위치를 물어볼 때 사용합니다." },
  { en: "Where do I return my tray?", ko: "쟁반은 어디에 반납하나요?", tip: "쟁반 반납 위치를 물어볼 때 사용합니다." },
  { en: "Can you wipe this table, please?", ko: "이 테이블 좀 닦아 주시겠어요?", tip: "테이블을 닦아달라고 할 때 사용합니다." },
  { en: "Is there an outlet near here?", ko: "이 근처에 콘센트가 있나요?", tip: "콘센트 위치를 물어볼 때 사용합니다." },
  { en: "Can I charge my phone here?", ko: "여기서 핸드폰 충전해도 되나요?", tip: "충전 가능 여부를 물어볼 때 사용합니다." },
  { en: "Do you have a charger I could borrow?", ko: "빌릴 수 있는 충전기가 있나요?", tip: "충전기를 빌릴 수 있는지 물어볼 때 사용합니다." },
  { en: "Is it okay if I sit here?", ko: "여기 앉아도 괜찮을까요?", tip: "자리에 앉아도 되는지 물어볼 때 사용합니다." },
  { en: "Are you open on Sundays?", ko: "일요일에도 영업하나요?", tip: "일요일 영업 여부를 물어볼 때 사용합니다." },
  { en: "What time do you open tomorrow?", ko: "내일 몇 시에 문 여나요?", tip: "내일 오픈 시간을 물어볼 때 사용합니다." },
  { en: "Do you have a loyalty program?", ko: "포인트 적립 프로그램이 있나요?", tip: "포인트 적립 여부를 물어볼 때 사용합니다." },
  { en: "Can I use this coupon?", ko: "이 쿠폰 사용할 수 있나요?", tip: "쿠폰 사용 가능 여부를 물어볼 때 사용합니다." },
  { en: "I have a discount code.", ko: "할인 코드가 있어요.", tip: "할인 코드가 있음을 알릴 때 사용합니다." },
  { en: "Is there a student discount?", ko: "학생 할인이 있나요?", tip: "학생 할인 여부를 물어볼 때 사용합니다." },
  { en: "Can I split the bill?", ko: "계산 나눠서 할 수 있나요?", tip: "분할 결제를 요청할 때 사용합니다." },
  { en: "I'll pay for everything.", ko: "제가 다 계산할게요.", tip: "일괄 결제를 원할 때 사용합니다." },
  { en: "Keep the change.", ko: "잔돈은 가지세요.", tip: "팁으로 잔돈을 줄 때 사용합니다." },
  { en: "Is tip included?", ko: "팁이 포함되어 있나요?", tip: "팁 포함 여부를 물어볼 때 사용합니다." },
  { en: "How much should I tip?", ko: "팁은 얼마를 줘야 하나요?", tip: "적정 팁 금액을 물어볼 때 사용합니다." },
  { en: "This isn't what I ordered.", ko: "이건 제가 주문한 게 아니에요.", tip: "주문한 메뉴가 잘못 나왔을 때 사용합니다." },
  { en: "My coffee is cold.", ko: "커피가 식었어요.", tip: "커피가 식었음을 알릴 때 사용합니다." },
  { en: "Can you make it hotter?", ko: "더 뜨겁게 해 주실 수 있나요?", tip: "더 뜨겁게 해달라고 할 때 사용합니다." },
  { en: "This is too sweet.", ko: "이건 너무 달아요.", tip: "음료가 너무 달 때 사용합니다." },
  { en: "Can you remake this, please?", ko: "이거 다시 만들어 주시겠어요?", tip: "음료를 다시 만들어달라고 할 때 사용합니다." },
  { en: "I dropped my drink.", ko: "음료를 쏟았어요.", tip: "음료를 쏟았음을 알릴 때 사용합니다." },
  { en: "Can I get a mop?", ko: "대걸레 좀 주시겠어요?", tip: "대걸레를 요청할 때 사용합니다." },
  { en: "I'm sorry for the mess.", ko: "어질러서 죄송합니다.", tip: "어질러서 미안함을 표현할 때 사용합니다." },
  { en: "It's okay, no problem.", ko: "괜찮아요, 문제없어요.", tip: "괜찮다고 말할 때 사용합니다." },
  { en: "Thank you for your help.", ko: "도와주셔서 감사합니다.", tip: "도움을 받았을 때 감사 인사를 합니다." },
  { en: "Have a nice day!", ko: "좋은 하루 보내세요!", tip: "헤어질 때 인사말입니다." },
  { en: "You too!", ko: "당신도요!", tip: "상대방의 인사에 답할 때 사용합니다." },
  { en: "I really like this cafe.", ko: "이 카페 정말 마음에 들어요.", tip: "카페가 마음에 듦을 표현할 때 사용합니다." },
  { en: "The coffee here is great.", ko: "여기 커피 정말 맛있네요.", tip: "커피 맛을 칭찬할 때 사용합니다." },
  { en: "I love the atmosphere.", ko: "분위기가 너무 좋아요.", tip: "분위기를 칭찬할 때 사용합니다." },
  { en: "Do you have any recommendations?", ko: "추천해 주실 만한 게 있나요?", tip: "메뉴 추천을 부탁할 때 사용합니다." },
  { en: "What's your favorite drink?", ko: "가장 좋아하는 음료가 뭐예요?", tip: "직원의 추천을 물어볼 때 사용합니다." },
  { en: "I'll try that one.", ko: "그걸로 먹어볼게요.", tip: "추천받은 메뉴를 선택할 때 사용합니다." }
];

const sentencesData = JSON.parse(fs.readFileSync('./src/sentences.json', 'utf-8'));
sentencesData.cafe = [...sentencesData.cafe, ...sentences];
fs.writeFileSync('./src/sentences.json', JSON.stringify(sentencesData, null, 2));

const dictionaryData = JSON.parse(fs.readFileSync('./src/dictionary.json', 'utf-8'));

const newWords = {
  "cappuccino": { "word": "cappuccino", "phonetic": "[ˌkæpʊˈtʃiːnoʊ]", "meanings": ["1. 카푸치노"] },
  "soy": { "word": "soy", "phonetic": "[sɔɪ]", "meanings": ["1. 콩", "2. 간장"] },
  "decaf": { "word": "decaf", "phonetic": "[ˈdiːkæf]", "meanings": ["1. 디카페인 커피"] },
  "carrot": { "word": "carrot", "phonetic": "[ˈkærət]", "meanings": ["1. 당근"] },
  "cake": { "word": "cake", "phonetic": "[keɪk]", "meanings": ["1. 케이크"] },
  "warmed": { "word": "warmed", "phonetic": "[wɔːrmd]", "meanings": ["1. 데워진"] },
  "customers": { "word": "customers", "phonetic": "[ˈkʌstəmərz]", "meanings": ["1. 고객들"] },
  "carrier": { "word": "carrier", "phonetic": "[ˈkæriər]", "meanings": ["1. 캐리어", "2. 운반인"] },
  "cup": { "word": "cup", "phonetic": "[kʌp]", "meanings": ["1. 컵"] },
  "taken": { "word": "taken", "phonetic": "[ˈteɪkən]", "meanings": ["1. 차지된", "2. 사용 중인"] },
  "anywhere": { "word": "anywhere", "phonetic": "[ˈeniwer]", "meanings": ["1. 어디든"] },
  "vegan": { "word": "vegan", "phonetic": "[ˈviːɡən]", "meanings": ["1. 비건", "2. 완전 채식주의자"] },
  "black": { "word": "black", "phonetic": "[blæk]", "meanings": ["1. 검은색", "2. 블랙 커피"] },
  "caramel": { "word": "caramel", "phonetic": "[ˈkærəməl]", "meanings": ["1. 카라멜"] },
  "macchiato": { "word": "macchiato", "phonetic": "[ˌmɑːkiˈɑːtoʊ]", "meanings": ["1. 마끼아또"] },
  "pump": { "word": "pump", "phonetic": "[pʌmp]", "meanings": ["1. 펌프"] },
  "vanilla": { "word": "vanilla", "phonetic": "[vəˈnɪlə]", "meanings": ["1. 바닐라"] },
  "sweet": { "word": "sweet", "phonetic": "[swiːt]", "meanings": ["1. 달콤한"] },
  "tea": { "word": "tea", "phonetic": "[tiː]", "meanings": ["1. 차"] },
  "green": { "word": "green", "phonetic": "[ɡriːn]", "meanings": ["1. 초록색", "2. 녹차"] },
  "smoothie": { "word": "smoothie", "phonetic": "[ˈsmuːði]", "meanings": ["1. 스무디"] },
  "flavors": { "word": "flavors", "phonetic": "[ˈfleɪvərz]", "meanings": ["1. 맛들"] },
  "strawberry": { "word": "strawberry", "phonetic": "[ˈstrɔːberi]", "meanings": ["1. 딸기"] },
  "bagel": { "word": "bagel", "phonetic": "[ˈbeɪɡl]", "meanings": ["1. 베이글"] },
  "cheese": { "word": "cheese", "phonetic": "[tʃiːz]", "meanings": ["1. 치즈"] },
  "toast": { "word": "toast", "phonetic": "[toʊst]", "meanings": ["1. 토스트", "2. 굽다"] },
  "croissant": { "word": "croissant", "phonetic": "[krwɑːˈsɑ̃ː]", "meanings": ["1. 크루아상"] },
  "muffins": { "word": "muffins", "phonetic": "[ˈmʌfɪnz]", "meanings": ["1. 머핀들"] },
  "blueberry": { "word": "blueberry", "phonetic": "[ˈbluːberi]", "meanings": ["1. 블루베리"] },
  "sandwich": { "word": "sandwich", "phonetic": "[ˈsændwɪtʃ]", "meanings": ["1. 샌드위치"] },
  "sandwiches": { "word": "sandwiches", "phonetic": "[ˈsændwɪtʃɪz]", "meanings": ["1. 샌드위치들"] },
  "turkey": { "word": "turkey", "phonetic": "[ˈtɜːrki]", "meanings": ["1. 칠면조"] },
  "salad": { "word": "salad", "phonetic": "[ˈsæləd]", "meanings": ["1. 샐러드"] },
  "comes": { "word": "comes", "phonetic": "[kʌmz]", "meanings": ["1. 오다", "2. 나오다"] },
  "paper": { "word": "paper", "phonetic": "[ˈpeɪpər]", "meanings": ["1. 종이"] },
  "sugar": { "word": "sugar", "phonetic": "[ˈʃʊɡər]", "meanings": ["1. 설탕"] },
  "artificial": { "word": "artificial", "phonetic": "[ˌɑːrtɪˈfɪʃl]", "meanings": ["1. 인공의"] },
  "sweeteners": { "word": "sweeteners", "phonetic": "[ˈswiːtnərz]", "meanings": ["1. 감미료들"] },
  "trash": { "word": "trash", "phonetic": "[træʃ]", "meanings": ["1. 쓰레기"] },
  "wipe": { "word": "wipe", "phonetic": "[waɪp]", "meanings": ["1. 닦다"] },
  "outlet": { "word": "outlet", "phonetic": "[ˈaʊtlet]", "meanings": ["1. 콘센트"] },
  "charge": { "word": "charge", "phonetic": "[tʃɑːrdʒ]", "meanings": ["1. 충전하다", "2. 요금을 청구하다"] },
  "charger": { "word": "charger", "phonetic": "[ˈtʃɑːrdʒər]", "meanings": ["1. 충전기"] },
  "borrow": { "word": "borrow", "phonetic": "[ˈbɑːroʊ]", "meanings": ["1. 빌리다"] },
  "okay": { "word": "okay", "phonetic": "[oʊˈkeɪ]", "meanings": ["1. 괜찮은"] },
  "student": { "word": "student", "phonetic": "[ˈstuːdnt]", "meanings": ["1. 학생"] },
  "everything": { "word": "everything", "phonetic": "[ˈevriθɪŋ]", "meanings": ["1. 모든 것"] },
  "change": { "word": "change", "phonetic": "[tʃeɪndʒ]", "meanings": ["1. 잔돈", "2. 변화"] },
  "tip": { "word": "tip", "phonetic": "[tɪp]", "meanings": ["1. 팁", "2. 끝"] },
  "hotter": { "word": "hotter", "phonetic": "[ˈhɑːtər]", "meanings": ["1. 더 뜨거운"] },
  "remake": { "word": "remake", "phonetic": "[ˌriːˈmeɪk]", "meanings": ["1. 다시 만들다"] },
  "dropped": { "word": "dropped", "phonetic": "[drɑːpt]", "meanings": ["1. 떨어뜨린"] },
  "drink": { "word": "drink", "phonetic": "[drɪŋk]", "meanings": ["1. 음료", "2. 마시다"] },
  "mop": { "word": "mop", "phonetic": "[mɑːp]", "meanings": ["1. 대걸레"] },
  "mess": { "word": "mess", "phonetic": "[mes]", "meanings": ["1. 엉망진창"] },
  "problem": { "word": "problem", "phonetic": "[ˈprɑːbləm]", "meanings": ["1. 문제"] },
  "really": { "word": "really", "phonetic": "[ˈriːəli]", "meanings": ["1. 정말로"] },
  "atmosphere": { "word": "atmosphere", "phonetic": "[ˈætməsfɪr]", "meanings": ["1. 분위기"] },
  "favorite": { "word": "favorite", "phonetic": "[ˈfeɪvərɪt]", "meanings": ["1. 가장 좋아하는"] }
};

Object.assign(dictionaryData, newWords);
fs.writeFileSync('./src/dictionary.json', JSON.stringify(dictionaryData, null, 2));

console.log("Added 90 sentences and words to cafe category.");
